-- Recoverable audit history for expert review edits.
create table if not exists public.review_change_history (
  id bigint generated by default as identity primary key,
  assignment_id uuid not null references public.review_assignments(id) on delete cascade,
  document_id uuid references public.review_documents(id) on delete set null,
  reviewer_user_id uuid not null references auth.users(id) on delete cascade,
  changed_by uuid not null references auth.users(id) on delete cascade,
  change_type text not null check (change_type in (
    'annotation_saved',
    'annotation_deleted',
    'progress_saved',
    'report_generated',
    'report_submitted',
    'report_delivered'
  )),
  target_id text,
  before_payload jsonb,
  after_payload jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists review_change_history_assignment_idx
  on public.review_change_history (assignment_id, occurred_at desc);
create index if not exists review_change_history_reviewer_idx
  on public.review_change_history (reviewer_user_id, occurred_at desc);

alter table public.review_change_history enable row level security;
revoke all on public.review_change_history from anon, authenticated;
grant all on public.review_change_history to service_role;
grant usage, select on sequence public.review_change_history_id_seq to service_role;
