"use strict";

const meta = (name) => document.querySelector(`meta[name="${name}"]`)?.content?.trim() || "";
const config = { supabaseUrl: meta("review-supabase-url").replace(/\/$/, ""), anonKey: meta("review-supabase-anon-key") };
config.production = Boolean(config.supabaseUrl && config.anonKey);
const REVIEW_APP_URL = "https://gyo6.kr/review/";
const $ = (selector, root = document) => root.querySelector(selector);
const escapeHtml = (value = "") => String(value ?? "").replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]);
const state = { mode: "demo", token: null, refreshToken: null, tokenExpiresAt: 0, refreshPromise: null, rows: [], experts: [], programs: [], subjects: [], documents: [], launch: { ready: false, enabled: false, pendingAssignments: 0 }, selectedId: null };

const DEMO_ROWS = [
  { id:"demo-1", reviewer:{name:"김○○ 교수",organization:"한국대학교",department:"법학과",positionTitle:"교수",email:"professor1@example.ac.kr",mobile:"010-0000-0001"},program:"공무원시험 대비",subject:"헌법",title:"헌법 핵심노트·모의고사 검수",period:"2026-08-11 — 2026-08-19",status:"reviewing",documentCount:4,completeDocumentCount:2,totalBlocks:48,checkedBlocks:31,opinionCount:12,lastActivityAt:new Date(Date.now()-42*60000).toISOString(),report:null,documents:[{title:"헌법 핵심노트 1차",complete:true,checkedBlocks:18,totalBlocks:18},{title:"실전 모의고사 제1회",complete:true,checkedBlocks:9,totalBlocks:9},{title:"실전 모의고사 제2회",complete:false,checkedBlocks:4,totalBlocks:11},{title:"실전 모의고사 제3회",complete:false,checkedBlocks:0,totalBlocks:10}] },
  { id:"demo-2", reviewer:{name:"이○○ 교수",organization:"대한대학교",department:"경제학과",positionTitle:"명예교수",email:"professor2@example.ac.kr",mobile:"010-0000-0002"},program:"공무원시험 대비",subject:"경제학원론",title:"경제학원론 핵심노트·모의고사 검수",period:"2026-08-11 — 2026-08-19",status:"submitted",documentCount:3,completeDocumentCount:3,totalBlocks:39,checkedBlocks:39,opinionCount:17,lastActivityAt:new Date(Date.now()-5*3600000).toISOString(),report:{id:"report-2",reportId:"REVIEW-DEMO2",sha256:"20c4a8…d781",deliveryStatus:"ready",fileName:"경제학원론_검수보고서.md"},documents:[{title:"경제학원론 핵심노트",complete:true,checkedBlocks:20,totalBlocks:20},{title:"모의고사 제1회",complete:true,checkedBlocks:10,totalBlocks:10},{title:"모의고사 제2회",complete:true,checkedBlocks:9,totalBlocks:9}] },
  { id:"demo-3", reviewer:{name:"박○○ 교수",organization:"국립대학교",department:"행정법학과",positionTitle:"교수",email:"professor3@example.ac.kr",mobile:"010-0000-0003"},program:"공무원시험 대비",subject:"행정법총론",title:"행정법총론 핵심노트·모의고사 검수",period:"2026-08-11 — 2026-08-19",status:"accepted",documentCount:3,completeDocumentCount:3,totalBlocks:42,checkedBlocks:42,opinionCount:21,lastActivityAt:new Date(Date.now()-26*3600000).toISOString(),report:{id:"report-3",reportId:"REVIEW-DEMO3",sha256:"a018d2…91ef",deliveryStatus:"delivered",fileName:"행정법총론_검수보고서.md",deliveredAt:new Date(Date.now()-20*3600000).toISOString()},documents:[{title:"행정법총론 핵심노트",complete:true,checkedBlocks:22,totalBlocks:22},{title:"모의고사 제1회",complete:true,checkedBlocks:10,totalBlocks:10},{title:"모의고사 제2회",complete:true,checkedBlocks:10,totalBlocks:10}] },
  { id:"demo-4", reviewer:{name:"최○○ 교수",organization:"미래대학교",department:"행정학과",positionTitle:"교수",email:"professor4@example.ac.kr",mobile:"010-0000-0004"},program:"공무원시험 대비",subject:"행정학개론",title:"행정학개론 핵심노트·모의고사 검수",period:"2026-08-11 — 2026-08-19",status:"reviewing",documentCount:4,completeDocumentCount:0,totalBlocks:51,checkedBlocks:8,opinionCount:2,lastActivityAt:new Date(Date.now()-76*3600000).toISOString(),attention:"최근 3일간 검수 기록 없음",report:null,documents:[{title:"행정학개론 핵심노트",complete:false,checkedBlocks:8,totalBlocks:25},{title:"모의고사 제1회",complete:false,checkedBlocks:0,totalBlocks:9},{title:"모의고사 제2회",complete:false,checkedBlocks:0,totalBlocks:9},{title:"모의고사 제3회",complete:false,checkedBlocks:0,totalBlocks:8}] }
];
const DEMO_CATALOG = {
  experts: DEMO_ROWS.map((row,index)=>({ id:`demo-expert-${index+1}`, ...row.reviewer, roleLabel:"외부 전문위원", active:true })),
  programs: [{id:"civil",name:"공무원시험 대비"},{id:"elementary",name:"초등교원임용고사 대비"},{id:"secondary",name:"중등교원임용고사 대비"}],
  subjects: [
    {id:"subject-constitution",programId:"civil",name:"헌법"},{id:"subject-economics",programId:"civil",name:"경제학원론"},{id:"subject-admin-law",programId:"civil",name:"행정법총론"},{id:"subject-admin",programId:"civil",name:"행정학개론"},
    {id:"subject-elementary",programId:"elementary",name:"초등 교육과정 통합"},{id:"subject-korean",programId:"secondary",name:"국어"}
  ],
  documents: [
    {id:"doc-con-note",subjectId:"subject-constitution",title:"헌법 핵심노트",kind:"핵심노트",version:"v1.2"},{id:"doc-con-mock1",subjectId:"subject-constitution",title:"헌법 실전 모의고사 제1회",kind:"모의고사",version:"v1.0"},
    {id:"doc-eco-note",subjectId:"subject-economics",title:"경제학원론 핵심노트",kind:"핵심노트",version:"v1.0"},{id:"doc-adminlaw-note",subjectId:"subject-admin-law",title:"행정법총론 핵심노트",kind:"핵심노트",version:"v1.0"},
    {id:"doc-admin-note",subjectId:"subject-admin",title:"행정학개론 핵심노트",kind:"핵심노트",version:"v1.0"},{id:"doc-elementary-note",subjectId:"subject-elementary",title:"초등 교육과정 통합",kind:"핵심노트",version:"v0.9"},{id:"doc-korean-note",subjectId:"subject-korean",title:"중등 국어 전공 핵심노트",kind:"핵심노트",version:"v0.8"}
  ]
};

function toast(message) { const element=$("#manager-toast"); element.textContent=message; element.classList.add("show"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>element.classList.remove("show"),2600); }
function applySession(session){ state.token=session.access_token; if(session.refresh_token)state.refreshToken=session.refresh_token; state.tokenExpiresAt=Date.now()+Math.max(60,Number(session.expires_in)||3600)*1000; }
async function refreshSession(){ if(!state.refreshToken)throw new Error("로그인 시간이 만료되었습니다. 다시 로그인해 주세요."); if(state.refreshPromise)return state.refreshPromise; state.refreshPromise=(async()=>{ const response=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey},body:JSON.stringify({refresh_token:state.refreshToken}),cache:"no-store",credentials:"omit"}); const session=await response.json().catch(()=>({})); if(!response.ok||!session.access_token)throw new Error("로그인 시간이 만료되었습니다. 다시 로그인해 주세요."); applySession(session); })(); try{await state.refreshPromise;}finally{state.refreshPromise=null;} }
async function api(action,payload={},retried=false) { if(state.refreshToken&&Date.now()>=state.tokenExpiresAt-60000)await refreshSession(); const response=await fetch(`${config.supabaseUrl}/functions/v1/review-content`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey,Authorization:`Bearer ${state.token}`},body:JSON.stringify({action,payload}),cache:"no-store",credentials:"omit"}); const body=await response.json().catch(()=>({})); if(response.status===401&&!retried&&state.refreshToken){await refreshSession();return api(action,payload,true);} if(!response.ok) throw new Error(body.error||"요청을 처리하지 못했습니다."); return body; }
async function sendOtp(email){ const response=await fetch(`${config.supabaseUrl}/auth/v1/otp`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey},body:JSON.stringify({email,create_user:false,email_redirect_to:`${location.origin}${location.pathname}`}),cache:"no-store"}); if(!response.ok) throw new Error("등록된 회사 관리자 이메일인지 확인해 주세요."); }
async function verifyOtp(email,token){ const response=await fetch(`${config.supabaseUrl}/auth/v1/verify`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey},body:JSON.stringify({email,token,type:"email"}),cache:"no-store"}); const body=await response.json().catch(()=>({})); if(!response.ok||!body.access_token) throw new Error(body.error_description||"인증번호를 확인해 주세요."); return body; }
function sessionFromMagicLink(){ if(!location.hash)return null; const params=new URLSearchParams(location.hash.slice(1)); const error=params.get("error_description"); const accessToken=params.get("access_token"); history.replaceState(null,"",`${location.pathname}${location.search}`); if(error)throw new Error(error); if(!accessToken)return null; return {access_token:accessToken,refresh_token:params.get("refresh_token")||"",expires_in:Number(params.get("expires_in"))||3600}; }

function reviewProgress(row){ if(!row.totalBlocks) return 0; const blockPart=(row.checkedBlocks/row.totalBlocks)*85; const documentPart=row.documentCount?(row.completeDocumentCount/row.documentCount)*15:0; return Math.min(100,Math.round(blockPart+documentPart)); }
function overallProgress(row){ const review=reviewProgress(row)*.8; const submitted=["submitted","accepted"].includes(row.status)?8:0; const report=row.report?6:0; const delivered=row.report?.deliveryStatus==="delivered"?6:0; return Math.round(review+submitted+report+delivered); }
function stageState(row,index){ const completed=[reviewProgress(row)>0,reviewProgress(row)===100,["submitted","accepted"].includes(row.status),Boolean(row.report),row.report?.deliveryStatus==="delivered"]; if(completed[index]) return "done"; const firstPending=completed.findIndex((value)=>!value); return index===firstPending?"current":""; }
function formatDate(value){ if(!value)return"기록 없음"; return new Intl.DateTimeFormat("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value)); }
function relativeTime(value){ if(!value)return"아직 활동 기록이 없습니다"; const hours=Math.floor((Date.now()-new Date(value).getTime())/3600000); if(hours<1)return"1시간 이내"; if(hours<24)return`${hours}시간 전`; return`${Math.floor(hours/24)}일 전`; }

function renderSummary(){ const uniqueExperts=new Set(state.rows.map(row=>row.reviewer.email||row.reviewer.name)).size; $("#summary-experts").textContent=uniqueExperts; $("#summary-reviewing").textContent=state.rows.filter(row=>row.status==="reviewing").length; $("#summary-submitted").textContent=state.rows.filter(row=>["submitted","accepted"].includes(row.status)).length; $("#summary-ready").textContent=state.rows.filter(row=>row.report?.deliveryStatus==="ready").length; $("#summary-delivered").textContent=state.rows.filter(row=>row.report?.deliveryStatus==="delivered").length; }
function renderProgramOptions(){ const current=$("#filter-program").value; const programs=[...new Set(state.rows.map(row=>row.program))]; $("#filter-program").innerHTML='<option value="all">전체 사업</option>'+programs.map(value=>`<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join(""); $("#filter-program").value=programs.includes(current)?current:"all"; }
function filteredRows(){ const program=$("#filter-program").value; const status=$("#filter-status").value; const query=$("#filter-search").value.trim().toLowerCase(); return state.rows.filter(row=>{ const matchesProgram=program==="all"||row.program===program; const actualStatus=row.attention?"attention":row.report?.deliveryStatus==="delivered"?"delivered":row.report?.deliveryStatus==="ready"?"ready":row.status; const matchesStatus=status==="all"||actualStatus===status; const haystack=`${row.reviewer.name} ${row.reviewer.organization} ${row.reviewer.department} ${row.program} ${row.subject}`.toLowerCase(); return matchesProgram&&matchesStatus&&(!query||haystack.includes(query)); }); }
function renderRows(){ const rows=filteredRows(); $("#result-count").textContent=`${rows.length}건`; $("#dashboard-empty").hidden=rows.length>0; $("#assignment-rows").innerHTML=rows.map(row=>{ const progress=reviewProgress(row); const stages=["검수 시작","자료 완료","최종 제출","보고서 생성","인계 완료"]; return `<tr><td><div class="expert"><strong>${escapeHtml(row.reviewer.name)}</strong><span>${escapeHtml(row.reviewer.organization||"")} · ${escapeHtml(row.reviewer.department||row.reviewer.positionTitle||"")}</span></div></td><td><div class="subject"><span>${escapeHtml(row.program)}</span><strong>${escapeHtml(row.subject)}</strong><small>${escapeHtml(row.title)}</small></div></td><td><div class="progress-cell"><div class="progress-copy"><strong>${progress}%</strong><span>전체 운영 ${overallProgress(row)}%</span></div><div class="progress-track"><i style="width:${progress}%"></i></div><small>문단 ${row.checkedBlocks}/${row.totalBlocks} · 자료 ${row.completeDocumentCount}/${row.documentCount}</small></div></td><td><div class="stage-line">${stages.map((label,index)=>`<div class="stage ${stageState(row,index)}"><i></i><span>${label}</span></div>`).join("")}</div></td><td><div class="activity"><span>${formatDate(row.lastActivityAt)}</span><small class="${row.attention?"attention-text":""}">${escapeHtml(row.attention||relativeTime(row.lastActivityAt))}</small></div></td><td><button class="row-action" data-detail-id="${escapeHtml(row.id)}" type="button">상세 확인</button></td></tr>`; }).join(""); }
function renderLaunchState(){ const button=$("#launch-review"); const pending=Number(state.launch?.pendingAssignments)||0; button.textContent=state.launch?.ready?`전문위원 일괄 시작 (${pending}건)`:"일괄 시작 잠금"; button.disabled=state.mode!=="production"||!state.launch?.ready||pending<1; }
function renderAll(){ renderSummary(); renderProgramOptions(); renderRows(); renderLaunchState(); $("#synced-at").textContent=`서버 기록 ${formatDate(new Date().toISOString())} 확인`; }

function enterDashboard(result){ state.rows=result.assignments||[]; state.experts=result.experts||[]; state.programs=result.programs||[]; state.subjects=result.subjects||[]; state.documents=result.documents||[]; state.launch=result.launch||{ready:false,enabled:false,pendingAssignments:0}; $("#manager-login").hidden=true; $("#manager-app").hidden=false; renderAll(); }
async function loadDashboard(){ enterDashboard(await api("managerDashboard")); }
async function launchAllReviews(){ const expected="전문위원 검수 일괄 시작"; const entered=prompt(`계약·전문위원 정보·최종 원고·기간을 모두 확인한 경우에만 아래 문구를 입력해 주세요.\n\n${expected}`); if(entered!==expected){toast("일괄 시작을 취소했습니다.");return;} const button=$("#launch-review"); button.disabled=true; try{const result=await api("managerLaunchAll",{confirmation:entered});await loadDashboard();toast(`${result.launchedExperts}명의 전문위원께 ${result.launchedAssignments}건의 공식 시작 안내를 발송했습니다.`);}catch(error){await loadDashboard().catch(()=>{});toast(error.message);} }
function selectedRow(){ return state.rows.find(row=>row.id===state.selectedId); }
function openDetail(id){ const row=state.rows.find(item=>item.id===id); if(!row)return; state.selectedId=id; $("#detail-title").textContent=`${row.reviewer.name} · ${row.subject}`; $("#detail-body").innerHTML=`<div class="detail-grid"><div class="detail-item"><span>전문위원</span><strong>${escapeHtml(row.reviewer.name)} · ${escapeHtml(row.reviewer.positionTitle||"")}</strong></div><div class="detail-item"><span>소속</span><strong>${escapeHtml(row.reviewer.organization||"")} ${escapeHtml(row.reviewer.department||"")}</strong></div><div class="detail-item"><span>연락</span><strong>${escapeHtml(row.reviewer.email||"")} · ${escapeHtml(row.reviewer.mobile||"")}</strong></div><div class="detail-item"><span>위촉 과목</span><strong>${escapeHtml(row.program)} / ${escapeHtml(row.subject)}</strong></div><div class="detail-item"><span>실제 검수 진도</span><strong>${reviewProgress(row)}% · 문단 ${row.checkedBlocks}/${row.totalBlocks}</strong></div><div class="detail-item"><span>보고서 인계</span><strong>${escapeHtml(row.report?.deliveryStatus==="delivered"?"전달 완료":row.report?"전달 대기":"최종 제출 전")}</strong></div></div><div class="detail-docs"><h3>자료별 실제 기록</h3>${(row.documents||[]).map(document=>`<div class="detail-doc"><strong>${escapeHtml(document.title)}</strong><span>${document.complete?"검토 완료":"검토 중"} · 문단 ${document.checkedBlocks}/${document.totalBlocks}</span></div>`).join("")}</div>`; $("#download-managed-report").disabled=!row.report; $("#mark-report-delivered").disabled=!row.report||row.report.deliveryStatus==="delivered"; $("#edit-assignment").disabled=row.status==="revoked"; $("#request-rereview").disabled=row.status==="revoked"||row.report?.deliveryStatus==="delivered"; $("#revoke-assignment").disabled=row.status==="revoked"||row.report?.deliveryStatus==="delivered"; $("#assignment-detail").showModal(); }
function downloadText(fileName,contents){ const blob=new Blob([contents],{type:"text/markdown;charset=utf-8"}); const url=URL.createObjectURL(blob); const anchor=document.createElement("a"); anchor.href=url; anchor.download=fileName; document.body.append(anchor); anchor.click(); anchor.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
async function downloadManagedReport(){ const row=selectedRow(); if(!row?.report)return; try{ if(state.mode==="demo"){ downloadText(row.report.fileName||"검수보고서.md",`# 표준 검수의견 보고서\n\n체험용 보고서: ${row.reviewer.name} / ${row.subject}\n`); }else{ const report=await api("managerGetReport",{exportId:row.report.id}); downloadText(report.fileName,report.markdown); } toast("표준 검수보고서를 내려받았습니다."); }catch(error){toast(error.message);} }
async function markDelivered(){ const row=selectedRow(); if(!row?.report||row.report.deliveryStatus==="delivered")return; if(!confirm("교재 제작 시스템에서 보고서 수신을 확인하셨습니까? 확인된 경우에만 전달 완료로 기록해 주세요."))return; try{ if(state.mode==="production")await api("markReportDelivered",{exportId:row.report.id}); row.report.deliveryStatus="delivered"; row.report.deliveredAt=new Date().toISOString(); renderAll(); openDetail(row.id); toast("보고서 전달 완료 기록을 저장했습니다."); }catch(error){toast(error.message);} }

function isoDate(offsetDays=0){ const date=new Date(); date.setDate(date.getDate()+offsetDays); return date.toISOString().slice(0,10); }
function openManualNotice(title,text){ $("#manual-notice-title").textContent=title; $("#manual-notice-text").value=text; $("#manual-notice-dialog").showModal(); }
function assignmentNotice(record){ const expert=state.experts.find(item=>item.id===record.expertUserId); const subject=state.subjects.find(item=>item.id===record.subjectId); const program=state.programs.find(item=>item.id===subject?.programId); return `[유한회사 설탕과소금 · 전문위원 검수 안내]\n\n${expert?.name||"전문위원"} 전문위원님께\n\n귀한 전문성으로 함께해 주셔서 깊이 감사드립니다.\n${program?.name||"시험 대비"} · ${subject?.name||"담당 과목"}의 검수 과제가 배정되었습니다.\n\n과제: ${record.title}\n기간: ${record.startsAt} ~ ${record.endsAt}\n\n아래 전용 워크룸에서 계약서에 기재하신 이메일로 인증한 뒤 검수를 진행해 주시면 감사하겠습니다.\n${REVIEW_APP_URL}\n\n일정이나 자료에 관하여 협의가 필요하시면 언제든 말씀해 주세요.\n\n유한회사 설탕과소금 드림\nadmin@gyo6.kr · 010-3534-7163`; }
function statusNotice(row,action){ const rereview=action==="rereview"; return `[유한회사 설탕과소금 · 전문위원 검수 안내]\n\n${row.reviewer.name} 전문위원님께\n\n${rereview?`${row.program} · ${row.subject} 검수 자료의 재검토를 정중히 부탁드립니다. 워크룸에서 확인하실 수 있도록 과제를 다시 열어 드렸습니다.`:`${row.program} · ${row.subject} 검수 위촉 종료 내용을 안내드립니다. 그동안 귀한 전문성으로 함께해 주셔서 깊이 감사드립니다.`}\n\n${rereview?`${REVIEW_APP_URL}\n\n`:""}일정이나 자료에 관하여 협의가 필요하시면 언제든 말씀해 주세요.\n\n유한회사 설탕과소금 드림\nadmin@gyo6.kr · 010-3534-7163`; }
function expertOptions(selected=""){ return state.experts.filter(item=>item.active!==false).map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===selected?"selected":""}>${escapeHtml(item.name)} · ${escapeHtml(item.organization||"")} ${escapeHtml(item.department||"")}</option>`).join(""); }
function programOptions(selected=""){ return state.programs.map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===selected?"selected":""}>${escapeHtml(item.name)}</option>`).join(""); }
function subjectOptions(programId,selected=""){ return state.subjects.filter(item=>item.programId===programId).map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===selected?"selected":""}>${escapeHtml(item.name)}</option>`).join(""); }
function renderDocumentPicker(subjectId,selectedIds=[]){ const available=state.documents.filter(item=>item.subjectId===subjectId); $("#assignment-documents").innerHTML=available.length?available.map(item=>`<label class="document-option"><input type="checkbox" value="${escapeHtml(item.id)}" ${selectedIds.includes(item.id)?"checked":""}><span>${escapeHtml(item.title)}<small>${escapeHtml(item.kind)} · ${escapeHtml(item.version||"")}</small></span></label>`).join(""):'<p class="form-note">이 과목에 등록된 검수 자료가 없습니다. 먼저 원고를 검수 자료로 등록해야 합니다.</p>'; }
function openExpertForm(expert=null){ $("#expert-form").reset(); $("#expert-dialog-title").textContent=expert?"전문위원 정보 확인·변경":"전문위원 등록"; $("#expert-id").value=expert?.id||""; $("#expert-name").value=expert?.name||""; $("#expert-email").value=expert?.email||""; $("#expert-mobile").value=expert?.mobile||""; $("#expert-organization").value=expert?.organization||""; $("#expert-department").value=expert?.department||""; $("#expert-position").value=expert?.positionTitle||""; $("#expert-active").checked=expert?.active!==false; $("#expert-dialog").showModal(); }
function openAssignmentForm(row=null){ $("#assignment-form").reset(); $("#assignment-dialog-title").textContent=row?"위촉 내용 확인·변경":"새 과목 위촉"; $("#assignment-id").value=row?.id||""; $("#assignment-expert").innerHTML=expertOptions(row?.reviewer?.id||""); const subject=state.subjects.find(item=>item.id===row?.subjectId)||state.subjects.find(item=>item.name===row?.subject); const programId=subject?.programId||state.programs[0]?.id||""; $("#assignment-program").innerHTML=programOptions(programId); $("#assignment-subject").innerHTML=subjectOptions(programId,subject?.id||""); $("#assignment-title").value=row?.title||""; const period=(row?.period||"").split(" — "); $("#assignment-start").value=period[0]||isoDate(); $("#assignment-end").value=period[1]||isoDate(14); $("#assignment-contract").value=row?.contractReference||"2026 시험 대비 외부 전문위원 검수용역"; $("#assignment-notify").checked=false; renderDocumentPicker(subject?.id||$("#assignment-subject").value,(row?.documents||[]).map(item=>item.id)); $("#assignment-expert").disabled=Boolean(row); $("#assignment-program").disabled=Boolean(row&&reviewProgress(row)>0); $("#assignment-subject").disabled=Boolean(row&&reviewProgress(row)>0); $("#assignment-dialog").showModal(); }
async function saveExpert(event){ event.preventDefault(); const record={ id:$("#expert-id").value||null,name:$("#expert-name").value.trim(),email:$("#expert-email").value.trim(),mobile:$("#expert-mobile").value.trim(),organization:$("#expert-organization").value.trim(),department:$("#expert-department").value.trim(),positionTitle:$("#expert-position").value.trim(),active:$("#expert-active").checked }; try{ if(state.mode==="production"){ const result=await api("managerUpsertExpert",record); toast(result.invitationSent?"전문위원 정보를 저장하고 이용 안내를 발송했습니다.":"전문위원 정보를 저장했습니다."); await loadDashboard(); }else{ if(record.id){ const index=state.experts.findIndex(item=>item.id===record.id); state.experts[index]={...state.experts[index],...record}; }else{ record.id=`demo-expert-${Date.now()}`; state.experts.push({...record,roleLabel:"외부 전문위원"}); } toast("전문위원 정보를 저장했습니다. (체험)"); } $("#expert-dialog").close(); renderAll(); }catch(error){toast(error.message);} }
async function saveAssignment(event){ event.preventDefault(); const documentIds=[...$("#assignment-documents").querySelectorAll('input[type="checkbox"]:checked')].map(input=>input.value); if(!documentIds.length){toast("전문위원님께 제공할 검수 자료를 한 건 이상 선택해 주세요.");return;} const record={ id:$("#assignment-id").value||null,expertUserId:$("#assignment-expert").value,subjectId:$("#assignment-subject").value,title:$("#assignment-title").value.trim(),startsAt:$("#assignment-start").value,endsAt:$("#assignment-end").value,contractReference:$("#assignment-contract").value.trim(),documentIds,sendNotification:$("#assignment-notify").checked }; const manualText=assignmentNotice(record); try{ if(state.mode==="production"){ const result=await api("managerSaveAssignment",record); toast(result.notificationSent?"위촉 내용을 저장하고 안내 이메일을 발송했습니다.":result.notificationStatus==="not_configured"?"위촉 내용을 저장했습니다. 수동 전달용 안내문을 확인해 주세요.":"위촉 내용을 저장했습니다."); await loadDashboard(); if(record.sendNotification&&result.notificationStatus==="not_configured")openManualNotice("위촉 안내문",manualText); }else{ const expert=state.experts.find(item=>item.id===record.expertUserId); const subject=state.subjects.find(item=>item.id===record.subjectId); const program=state.programs.find(item=>item.id===subject?.programId); const docs=state.documents.filter(item=>documentIds.includes(item.id)).map(item=>({...item,totalBlocks:0,checkedBlocks:0,complete:false})); if(record.id){ const index=state.rows.findIndex(item=>item.id===record.id); state.rows[index]={...state.rows[index],title:record.title,period:`${record.startsAt} — ${record.endsAt}`,contractReference:record.contractReference,documents:docs,documentCount:docs.length}; }else{ state.rows.push({id:`demo-${Date.now()}`,reviewer:expert,program:program?.name||"검수 사업",subject:subject?.name||"담당 과목",title:record.title,period:`${record.startsAt} — ${record.endsAt}`,contractReference:record.contractReference,status:"assigned",documentCount:docs.length,completeDocumentCount:0,totalBlocks:0,checkedBlocks:0,opinionCount:0,lastActivityAt:null,report:null,documents:docs}); } toast("위촉 내용과 안내 이메일 발송 요청을 저장했습니다. (체험)"); } $("#assignment-dialog").close(); renderAll(); }catch(error){toast(error.message);} }
async function changeAssignment(action){ const row=selectedRow(); if(!row)return; const messages={rereview:"전문위원님께 재검토를 요청하고 과제를 다시 열어 드리겠습니까?",revoke:"위촉을 종료하면 전문위원님의 자료 접근이 즉시 종료됩니다. 계속하시겠습니까?"}; if(!confirm(messages[action]))return; const manualText=statusNotice(row,action); try{ let result={notificationSent:state.mode==="demo",notificationStatus:state.mode==="demo"?"sent":"skipped"}; if(state.mode==="production"){result=await api("managerChangeAssignmentStatus",{assignmentId:row.id,command:action,endsAt:action==="rereview"?isoDate(14):null,sendNotification:true});await loadDashboard();}else{row.status=action==="revoke"?"revoked":"returned";if(action==="rereview")row.attention=null;renderAll();} $("#assignment-detail").close(); const baseMessage=action==="revoke"?"위촉 종료 기록을 저장했습니다.":"재검토 요청을 기록했습니다."; toast(result.notificationSent?`${baseMessage} 안내 이메일도 발송했습니다.`:result.notificationStatus==="not_configured"?`${baseMessage} 수동 전달용 안내문을 확인해 주세요.`:baseMessage); if(result.notificationStatus==="not_configured")openManualNotice(action==="revoke"?"위촉 종료 안내문":"재검토 안내문",manualText); }catch(error){toast(error.message);} }

$("#manager-demo").addEventListener("click",()=>enterDashboard({assignments:structuredClone(DEMO_ROWS).map((row,index)=>({...row,reviewer:{...row.reviewer,id:`demo-expert-${index+1}`},subjectId:DEMO_CATALOG.subjects[index]?.id||null,programId:"civil",contractReference:"2026 공무원시험 대비 외부 전문위원 검수용역"})),...structuredClone(DEMO_CATALOG)}));
$("#manager-login-form").addEventListener("submit",async(event)=>{event.preventDefault(); if(!config.production){toast("현재는 운영 화면 확인 모드입니다. 아래 확인 버튼을 이용해 주세요.");return;} try{await sendOtp($("#manager-email").value.trim());$("#manager-otp-row").hidden=false;$("#manager-otp").focus();toast("관리자 이메일로 인증번호를 보냈습니다.");}catch(error){toast(error.message);}});
$("#manager-otp-submit").addEventListener("click",async()=>{try{const session=await verifyOtp($("#manager-email").value.trim(),$("#manager-otp").value.trim());state.mode="production";applySession(session);await loadDashboard();}catch(error){toast(error.message);}});
$("#refresh-dashboard").addEventListener("click",async()=>{if(state.mode==="demo"){renderAll();toast("체험 기록을 새로고침했습니다.");return;}try{await loadDashboard();toast("최신 서버 기록을 불러왔습니다.");}catch(error){toast(error.message);}});
$("#launch-review").addEventListener("click",launchAllReviews);
[$("#filter-program"),$("#filter-status")].forEach(element=>element.addEventListener("change",renderRows));
$("#filter-search").addEventListener("input",renderRows);
$("#assignment-rows").addEventListener("click",event=>{const button=event.target.closest("[data-detail-id]");if(button)openDetail(button.dataset.detailId);});
$("#detail-close").addEventListener("click",()=>$("#assignment-detail").close());
$("#download-managed-report").addEventListener("click",downloadManagedReport);
$("#mark-report-delivered").addEventListener("click",markDelivered);
$("#new-expert").addEventListener("click",()=>openExpertForm());
$("#new-assignment").addEventListener("click",()=>openAssignmentForm());
$("#expert-form").addEventListener("submit",saveExpert);
$("#assignment-form").addEventListener("submit",saveAssignment);
$("#assignment-program").addEventListener("change",()=>{ $("#assignment-subject").innerHTML=subjectOptions($("#assignment-program").value); renderDocumentPicker($("#assignment-subject").value); });
$("#assignment-subject").addEventListener("change",()=>renderDocumentPicker($("#assignment-subject").value));
$("#copy-manual-notice").addEventListener("click",async()=>{ try{await navigator.clipboard.writeText($("#manual-notice-text").value);toast("안내문을 복사했습니다.");}catch{ $("#manual-notice-text").focus();$("#manual-notice-text").select();toast("선택된 안내문을 복사해 주세요.");} });
document.addEventListener("click",event=>{ const button=event.target.closest("[data-close-dialog]"); if(button)$("#"+button.dataset.closeDialog).close(); });
$("#edit-assignment").addEventListener("click",()=>{const row=selectedRow();if(row){$("#assignment-detail").close();openAssignmentForm(row);}});
$("#edit-expert").addEventListener("click",()=>{const row=selectedRow();const expert=state.experts.find(item=>item.id===row?.reviewer?.id);if(expert){$("#assignment-detail").close();openExpertForm(expert);}});
$("#request-rereview").addEventListener("click",()=>changeAssignment("rereview"));
$("#revoke-assignment").addEventListener("click",()=>changeAssignment("revoke"));

if(config.production){ $("#manager-demo").hidden=true; try{ const magicLinkSession=sessionFromMagicLink(); if(magicLinkSession){state.mode="production";applySession(magicLinkSession);loadDashboard().catch(error=>toast(error.message));} }catch(error){toast(error.message);} }
