import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const PROMO_WORKER_KEY = Deno.env.get("PROMO_WORKER_KEY") ?? "";
const ALLOWED_ORIGINS = (Deno.env.get("PROMO_ALLOWED_ORIGINS") ?? "https://gyo6.kr,http://127.0.0.1:4181,http://localhost:4181")
  .split(",").map((value) => value.trim()).filter(Boolean);
const MAX_REQUEST_CHARS = 250_000;
const INTERNAL_CATEGORIES = new Set(["비용통제", "핵심자산", "조사", "통제"]);
const VALID_STATUS = new Set(["draft", "review", "approved", "hold", "rejected"]);
const VALID_ADAPTERS = new Set(["browser", "email_connector", "official_api"]);
const VALID_RESULTS = new Set(["awaiting_automation", "sent", "published", "failed", "needs_attention", "rejected_by_platform"]);
const VALID_ENGINE_STAGES = new Set(["queued", "drafting", "verifying", "waiting_external", "ready_for_approval", "needs_owner", "approved", "stopped"]);
const GATE_LABELS: Record<string,string> = {fact:"사실 근거 대조",review:"외부 검토 범위 확인",product:"로그인 없는 무료 공개 확인",disclosure:"회사 관계·무협찬 표시 확인",rules:"최신 매체 규정·무료 경로 확인",utm:"추적 링크 접속 확인",privacy:"제3자 개인정보 제거 확인"};

type SeedItem = {
  id: string; title: string; channel: string; category: string; due?: string; status: string; risk: string;
  sourceRef: string; notes: string; requiredGates: string[]; gates: Record<string, boolean>; route: string;
};

const DEFAULT_ITEMS: SeedItem[] = [
  {id:"PR-01",title:"전국 무료제보용 표준 보도자료",channel:"언론사 공식 제보창구",category:"언론",due:"2026-08-17",status:"draft",risk:"중",sourceRef:"매체별_기사보도자료_완성본_v1.md §2",notes:"유료 배포서비스 제외. 외부 전공검토·무료범위 대괄호 제거 후 승인",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:false,review:false,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"공식 무료 제보창구"},
  {id:"PR-02",title:"이로운넷 사회적 가치 기사안",channel:"이로운넷",category:"언론",due:"2026-08-16",status:"review",risk:"중",sourceRef:"매체별_기사보도자료_완성본_v1.md §3",notes:"협의 결과물·SNS·리포트 범위를 서면 확정하되 담당자 개인정보는 기록하지 않음",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:true,review:false,product:false,disclosure:false,rules:true,utm:false,privacy:true},route:"담당 기자 맞춤 피치"},
  {id:"PR-03",title:"AI 전문매체 인간책임형 기사안",channel:"AI타임스 등",category:"언론",due:"2026-08-18",status:"draft",risk:"상",sourceRef:"매체별_기사보도자료_완성본_v1.md §4",notes:"모델·버전·실행일과 비식별 오탐 사례 필수",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:false,review:false,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"AI 전문매체 공식 제보"},
  {id:"PR-04",title:"스타트업 매체 6문장 무료 피치",channel:"플래텀·벤처스퀘어",category:"언론",due:"2026-08-18",status:"draft",risk:"중",sourceRef:"매체별_기사보도자료_완성본_v1.md §5",notes:"비용 없는 편집취재만 진행. 유료기사·유료배포 조건이면 제외",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:true,review:false,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"공식 무료 제보창구"},
  {id:"PR-05",title:"교육전문매체 품질관리 제안",channel:"교육전문지",category:"언론",due:"2026-08-18",status:"draft",risk:"중",sourceRef:"매체별_기사보도자료_완성본_v1.md §6",notes:"개인을 특정할 수 없게 수정 전후 사례 3건 첨부",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:false,review:false,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"교육전문지 편집부 제안"},
  {id:"PR-06",title:"경주 직업교육인 지역 기사안",channel:"경주·경북 지역지",category:"언론",due:"2026-08-16",status:"review",risk:"낮음",sourceRef:"매체별_기사보도자료_완성본_v1.md §7",notes:"비식별 표창 사본과 방송 화면만 사용, 프로그램명 단정 금지",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"경주·경북 지역지 공식 제보"},
  {id:"PR-07",title:"과거 보도 매체 17년 뒤 후속기사",channel:"과거 보도 매체 현재 편집부",category:"언론",due:"2026-08-16",status:"review",risk:"낮음",sourceRef:"대표_증빙기반_인물기사_PR팩_v1.md §6",notes:"학생 개발·대표 지도 사실을 정확히 사용. 과거 학생 이름·얼굴·개인 연락처가 든 원본은 첨부 금지",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"과거 보도 매체 현재 편집부 공식 제보"},
  {id:"PR-08",title:"생애전환 인물기사 소프트 피치",channel:"종합지 생애전환 기획·경제부",category:"언론",due:"2026-08-17",status:"review",risk:"중",sourceRef:"대표_증빙기반_인물기사_PR팩_v1.md §7",notes:"현재는 성공담이 아닌 과정 제안. 30일·60일 실제 수치로 후속 제안",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:true,review:false,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"생애전환 기획 공식 제보"},
  {id:"PR-09",title:"지역 방송 과거-현재 영상기사 피치",channel:"지역 방송 공식 제보 경로",category:"언론",due:"2026-08-17",status:"draft",risk:"중",sourceRef:"대표_증빙기반_인물기사_PR팩_v1.md §9",notes:"학생 이름·얼굴을 완전히 제거한 과거 화면과 현재 무료 화면·수정 장면만 사용",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:false},route:"지역 방송 공식 제보"},
  {id:"CM-01",title:"허가된 공무원 카페 공식 안내",channel:"소형 공무원·과목 카페",category:"커뮤니티",due:"2026-08-17",status:"draft",risk:"중",sourceRef:"커뮤니티_확장운영안_v1.md §5-B",notes:"운영자 허가 여부만 기록하고 이름·계정·연락처 캡처는 보관하지 않음",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:false,review:false,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"운영자 사전허가"},
  {id:"CM-02",title:"맘카페 무료 사업자 게시판 테스트",channel:"지역 맘카페",category:"커뮤니티",due:"2026-08-18",status:"review",risk:"상",sourceRef:"커뮤니티_확장운영안_v1.md §5-C",notes:"무료 사업자 게시판 또는 운영자 무료 허가만. 비용 조건이면 제외",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"무료 사업자 게시판"},
  {id:"CM-03",title:"디시 7급 갤러리 운영자 허가 문의",channel:"디시인사이드",category:"허가문의",due:"2026-08-17",status:"review",risk:"상",sourceRef:"커뮤니티_확장운영안_v1.md §5-E",notes:"홍보글은 금지. 이 항목은 허가 문의문만 승인 가능",requiredGates:["fact","disclosure","rules","privacy"],gates:{fact:true,disclosure:true,rules:true,privacy:true},route:"운영자 허가 문의"},
  {id:"CM-04",title:"블라인드 직접홍보·제작자 공개형 도전",channel:"블라인드 직접 홍보",category:"직접홍보",due:"2026-08-17",status:"review",risk:"중",sourceRef:"커뮤니티_확장운영안_v1.md §5-G",notes:"직접 홍보 주제 최신 규칙과 대표 계정 인증 가능성을 확인. 첫 두 문장에 대표·제작자 관계 표시",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"대표·제작자 관계 공개형 글"},
  {id:"CM-05",title:"공드림 무료 공식안내 사전허가",channel:"공드림",category:"무료진입",due:"2026-08-18",status:"draft",risk:"상",sourceRef:"대형_수험커뮤니티_무료진입_제휴조사_v1.md §1",notes:"회사관계 표시와 운영자 사전허가를 전제로 진행",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"운영자 사전허가"},
  {id:"CM-06",title:"닥공사 비용 없는 제휴·자료기증 문의",channel:"닥공사",category:"무료진입",due:"2026-08-18",status:"draft",risk:"상",sourceRef:"대형_수험커뮤니티_무료진입_제휴조사_v1.md §1",notes:"비제휴 홍보 금지. 무료 선검토·자료기증·검증기고 중 허용형태만 1회 문의",requiredGates:["fact","product","disclosure","rules","privacy"],gates:{fact:true,product:false,disclosure:true,rules:true,privacy:true},route:"무료 제휴 문의"},
  {id:"CM-07",title:"독공사·독취사 무료 사전동의 문의",channel:"독공사·독취사",category:"무료진입",due:"2026-08-18",status:"review",risk:"상",sourceRef:"대형_수험커뮤니티_무료진입_제휴조사_v1.md §1",notes:"일반 게시 금지, 운영자 선검토·자료기증 가능성만 문의",requiredGates:["fact","product","disclosure","rules","privacy"],gates:{fact:true,product:false,disclosure:true,rules:true,privacy:true},route:"운영자 선검토·자료기증 문의"},
  {id:"CM-08",title:"9꿈사 최신 이용수칙 직접 확인",channel:"9꿈사",category:"조사",due:"2026-08-18",status:"hold",risk:"상",sourceRef:"대형_수험커뮤니티_무료진입_제휴조사_v1.md §1",notes:"최신 세부규정 확인 전 게시·문의 금지",requiredGates:["rules","privacy"],gates:{rules:false,privacy:true},route:"최신 이용수칙 확인"},
  {id:"CM-09",title:"공취사 무료 편집협력·대체경로 탐색",channel:"공취사",category:"무료진입",due:"2026-08-18",status:"review",risk:"중",sourceRef:"대형_수험커뮤니티_무료진입_제휴조사_v1.md §6",notes:"유료 광고폼만 제외. 무료 기고·자료기증·질문답변·검색형 경로를 계속 탐색",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"무료 편집협력 문의"},
  {id:"CM-10",title:"관계 공개형 개인계정 활용",channel:"전체 커뮤니티",category:"직접홍보",due:"2026-08-17",status:"review",risk:"중",sourceRef:"무료_전문공개_최대진입전략_v1.md §5",notes:"개인계정을 배제하지 않되 첫 두 문장에 대표·제작자·회사 관계를 밝히고 허용 구역에서만 사용",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:true},route:"관계 공개형 개인 게시"},
  {id:"ASSET-01",title:"4과목 대표 단원 전문+모의고사 1회 전체 공개 검증",channel:"무료 공개 URL",category:"핵심자산",due:"2026-08-17",status:"draft",risk:"중",sourceRef:"무료_전문공개_최대진입전략_v1.md §1",notes:"회원가입·로그인·개인정보 제출·결제·횟수 제한이 없어야 문구 사용 가능",requiredGates:["fact","review","product","privacy","utm"],gates:{fact:false,review:false,product:false,privacy:true,utm:false},route:"로그인 없는 무료 랜딩"},
  {id:"COST-01",title:"유료홍보 0원·운영경비 3단계 승인",channel:"전체",category:"비용통제",status:"approved",risk:"낮음",sourceRef:"무광고_수작업홍보_비용승인원칙.md",notes:"광고·유료기사·유료배포·유료게시·협찬·수수료는 집행하지 않음",requiredGates:["rules","privacy"],gates:{rules:true,privacy:true},route:"원칙 상시 적용"},
  {id:"PT-01",title:"소형 공부계정 30곳 제휴 제안",channel:"인스타·블로그·스터디",category:"제휴",due:"2026-08-17",status:"draft",risk:"중",sourceRef:"커뮤니티_확장운영안_v1.md §5-D",notes:"무차별 DM 금지, 계정별 구체적 이유와 1회 연락",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"개별 선검토 제안"},
  {id:"OWN-01",title:"검토 전후·무료문제 주간 시리즈",channel:"공식 SNS·블로그·유튜브",category:"자체채널",due:"2026-08-17",status:"draft",risk:"낮음",sourceRef:"커뮤니티_확장운영안_v1.md §4",notes:"주 7개 반복 포맷, 플랫폼별 도입 재작성, 검토자·제보자 신상 비공개",requiredGates:["fact","review","product","disclosure","rules","utm","privacy"],gates:{fact:false,review:false,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"공식 블로그 원문"},
  {id:"SHARE-01",title:"실제 이용자·지인 자발공유 확산장치",channel:"웹·카카오톡·문자·SNS",category:"자발공유",due:"2026-08-17",status:"draft",risk:"낮음",sourceRef:"커뮤니티_확장운영안_v1.md §5-H",notes:"사실 중심 공유문구와 채널별 UTM만 제공. 후기 대필·보상·공유자 개인정보 수집 금지",requiredGates:["fact","product","disclosure","rules","utm","privacy"],gates:{fact:true,product:false,disclosure:true,rules:true,utm:false,privacy:true},route:"웹 공유 버튼·중립 전달문구"}
];

const CONTENT_OVERRIDES: Record<string, string> = {
  "PR-01": "광고비 대신 검토 과정과 무료 원문을 공개한 작은 교육회사의 실험이 시작됐습니다.\n\n유한회사 설탕과소금 공직시험연구소는 헌법·행정법·행정학·경제학의 대표 단원 전문과 모의고사 1회 전체를 로그인·결제 없이 공개합니다. 외부 전공 전문가가 검토한 자료를 두 AI가 오류 후보 중심으로 교차 점검하고, 최종 판단과 책임은 사람이 맡습니다.\n\n취재·검토에 필요한 무료 원문과 비식별 근거자료를 제공할 수 있습니다.",
  "PR-02": "정보 접근 격차를 줄이는 무료 수험자료 공개 실험을 제안합니다. 4과목 대표 단원과 모의고사 1회 전체를 조건 없이 공개하고, 검토 범위와 정정 절차도 함께 보여 줍니다.\n\n성과를 미리 단정하지 않고 실제 이용·오류 제보·수정 기록을 공개하는 사회적 가치 관점의 취재안입니다.",
  "PR-03": "두 개의 최신 AI와 외부 전공 전문가가 만난 인간책임형 검토 실험입니다. AI는 인증자가 아니라 오류 후보 탐지와 교차 점검 도구이며, 사람이 최종 판정합니다.\n\n모델·버전·실행일, 비식별 오탐 사례, 수정 기록을 재현 가능한 범위에서 공개합니다.",
  "PR-04": "신생 공직시험연구소가 대형 교육업체에 가격이 아닌 검증 투명성으로 도전합니다. 4과목 대표 단원과 모의고사 1회 전체를 조건 없이 공개합니다. 외부 전공 전문가 검토 뒤 두 AI로 오류 후보를 재점검하고 사람이 최종 판정합니다. 유료 기사나 협찬이 아닌 편집 취재만 제안합니다.",
  "PR-07": "2009년 학생들의 교육 소프트웨어 개발을 지도했던 직업교육인이 2026년 작은 교육회사를 세워 사람과 AI의 검토 과정을 공개합니다. 학생들이 개발했고 대표는 지도교사였다는 사실을 정확히 밝히며, 당시 학생의 이름과 얼굴은 사용하지 않습니다.",
  "PR-08": "아직 성공담을 말할 단계가 아니라는 점부터 밝힙니다. 오래 가르친 사람이 작은 자본과 적은 인력으로 무엇을 포기하고 무엇을 공개하기로 했는지, 무료 원문과 첫 수험생의 평가를 기다리는 과정을 취재 제안합니다.",
  "CM-01": "유한회사 설탕과소금 공직시험연구소입니다. 운영자 허가를 받아 무료 학습자료를 안내드립니다. 헌법·행정법·행정학·경제학 대표 단원 전문과 모의고사 1회 전체를 회원가입·결제 없이 확인할 수 있습니다.",
  "CM-03": "유한회사 설탕과소금 공직시험연구소입니다. 7급 수험생에게 로그인 없이 공개한 무료 자료를 안내할 수 있는 공식 절차가 있는지 문의드립니다. 허용되지 않으면 게시하지 않겠습니다.",
  "CM-04": "유한회사 설탕과소금 공직시험연구소를 운영하며 자료 제작에 참여한 대표입니다. 먼저 믿어 달라는 말 대신 헌법·행정법·행정학·경제학 대표 단원과 모의고사 1회분 전체를 로그인 없이 열었습니다.\n\n본인이나 주변의 7급 준비생이 무료분만 보고 냉정하게 평가해 주시면 좋겠습니다. 이 글은 제작자인 제가 직접 올리는 홍보 글이며 게시·소개 대가는 없습니다.",
  "CM-10": "자료를 만든 유한회사 설탕과소금 공직시험연구소 대표임을 먼저 밝힙니다. 7급을 준비하는 분이 직접 판단할 수 있도록 4과목 대표 단원과 모의고사 1회 전체를 로그인 없이 공개했습니다. 무료분만 확인해 보고 도움이 되는지는 각자 판단해 주세요.",
  "SHARE-01": "7급을 준비하는 분께 공유해 주세요. 헌법·행정법·행정학·경제학 대표 단원과 모의고사 1회분 문제·정답·해설 전체를 로그인 없이 볼 수 있습니다. 제공: 유한회사 설탕과소금 공직시험연구소. 공유자의 개인정보는 수집하지 않습니다."
};

function cors(origin: string | null) {
  const allowed = origin && ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  return {"Access-Control-Allow-Origin":allowed,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-promo-worker-key","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"600","Cache-Control":"no-store, no-cache, must-revalidate, private","Content-Type":"application/json; charset=utf-8","Referrer-Policy":"no-referrer","Vary":"Origin"};
}
function json(body: unknown, status: number, origin: string | null) { return new Response(JSON.stringify(body), { status, headers: cors(origin) }); }
function bearer(request: Request) { const value=request.headers.get("Authorization")??"";return value.startsWith("Bearer ")?value.slice(7):""; }
function cleanText(value: unknown, max=10000) { return String(value??"").trim().slice(0,max); }
function cleanTextArray(value: unknown, maxItems=20, maxLength=1000) { return Array.isArray(value)?value.slice(0,maxItems).map(v=>cleanText(v,maxLength)).filter(Boolean):[]; }
function sameSecret(received: string, expected: string) { if(!expected||received.length!==expected.length)return false;let diff=0;for(let i=0;i<received.length;i++)diff|=received.charCodeAt(i)^expected.charCodeAt(i);return diff===0; }
function canonical(value: unknown): unknown { if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==="object")return Object.fromEntries(Object.keys(value as Record<string,unknown>).sort().map(k=>[k,canonical((value as Record<string,unknown>)[k])]));return value; }
async function sha256(value: unknown) { const bytes=new TextEncoder().encode(JSON.stringify(canonical(value)));const hash=await crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(hash)).map(v=>v.toString(16).padStart(2,"0")).join(""); }
function defaultContent(item: SeedItem) { return CONTENT_OVERRIDES[item.id] ?? `${item.title}\n\n${item.notes}\n\n유한회사 설탕과소금 공직시험연구소의 관계를 공개하며, 비용·협찬·수수료 없는 허용 경로로만 제안합니다.`; }
function delivery(value: unknown) { const raw=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};const adapter=cleanText(raw.adapter,40)||"browser";if(!VALID_ADAPTERS.has(adapter))throw new Error("허용되지 않은 실행 방식입니다.");if(Number(raw.cost??0)!==0)throw new Error("유료홍보는 승인할 수 없습니다.");return{adapter,destination:cleanText(raw.destination,2000),scheduledAt:cleanText(raw.scheduledAt,80)||null,attachments:cleanTextArray(raw.attachments,20,2000),cost:0}; }
function gates(value: unknown) { if(!value||typeof value!=="object"||Array.isArray(value))return{};return Object.fromEntries(Object.entries(value as Record<string,unknown>).slice(0,30).map(([k,v])=>[cleanText(k,40),v===true])); }
function evidence(value: unknown) { if(!Array.isArray(value))return[];return value.slice(0,80).map(entry=>{const raw=entry&&typeof entry==="object"&&!Array.isArray(entry)?entry as Record<string,unknown>:{};return{gate:cleanText(raw.gate,40),reference:cleanText(raw.reference,2000),summary:cleanText(raw.summary,1000),checkedAt:cleanText(raw.checkedAt,80),kind:cleanText(raw.kind,40)||"official"};}).filter(entry=>entry.gate&&entry.reference&&entry.checkedAt); }
function isReady(row: Record<string,any>, nextGates=row.gates, nextContent=row.content, nextRoute=row.route, nextDelivery=row.delivery) { const missing=(Array.isArray(row.required_gates)?row.required_gates:[]).filter((key:string)=>nextGates?.[key]!==true);const external=!INTERNAL_CATEGORIES.has(row.category);return Boolean(!missing.length&&cleanText(nextContent,60000)&&cleanText(nextRoute,1000)&&(!external||cleanText(nextDelivery?.destination,2000))&&Number(nextDelivery?.cost??0)===0); }
function nextGate(row: Record<string,any>, nextGates=row.gates) { const key=(Array.isArray(row.required_gates)?row.required_gates:[]).find((candidate:string)=>nextGates?.[candidate]!==true);return key?GATE_LABELS[key]||`${key} 확인`:(!cleanText(row.content,60000)?"매체별 문안 작성":!cleanText(row.route,1000)?"허용된 무료 경로 확인":!INTERNAL_CATEGORIES.has(row.category)&&!cleanText(row.delivery?.destination,2000)?"정확한 공식 수신처 확인":"대표 승인 대기"); }
function mapItem(row: Record<string,any>) { return{id:row.id,title:row.title,channel:row.channel,category:row.category,risk:row.risk,status:row.status,due:row.due,sourceRef:row.source_ref,notes:row.notes,content:row.content,route:row.route,requiredGates:row.required_gates,gates:row.gates,delivery:row.delivery,approvedHash:row.approved_hash,approvedAt:row.approved_at,updatedAt:row.updated_at,engineStage:row.engine_stage,engineLastAction:row.engine_last_action,engineNextAction:row.engine_next_action,engineBlocker:row.engine_blocker,engineLastRunAt:row.engine_last_run_at,engineNextRunAt:row.engine_next_run_at,engineAttemptCount:row.engine_attempt_count,engineEvidence:row.engine_evidence}; }
function mapJob(row: Record<string,any>) { return{id:row.id,itemId:row.item_id,status:row.status,approvedHash:row.approved_hash,approvedAt:row.approved_at,executeAfter:row.execute_after,claimedAt:row.claimed_at,result:row.result,finishedAt:row.finished_at,updatedAt:row.updated_at}; }
function mapWorker(row: Record<string,any>) { return{workerId:row.worker_id,label:row.label,status:row.status,version:row.version,message:row.message,capabilities:row.capabilities,lastSeenAt:row.last_seen_at}; }

async function ensureManager(admin: ReturnType<typeof createClient>, userId: string) { const {data,error}=await admin.from("review_profiles").select("user_id,role,active").eq("user_id",userId).single();if(error||!data?.active||!["manager","admin"].includes(data.role))throw new Error("회사 운영담당자 권한이 필요합니다.");return data; }
async function seedDefaults(admin: ReturnType<typeof createClient>) { const {count,error}=await admin.from("promo_items").select("id",{count:"exact",head:true});if(error)throw error;if((count??0)>0)return;const rows=DEFAULT_ITEMS.map(item=>({id:item.id,title:item.title,channel:item.channel,category:item.category,risk:item.risk,status:item.status,due:item.due||null,source_ref:item.sourceRef,notes:item.notes,content:defaultContent(item),route:item.route,required_gates:item.requiredGates,gates:item.gates,delivery:{adapter:"browser",destination:"",scheduledAt:null,attachments:[],cost:0}}));const {error:insertError}=await admin.from("promo_items").insert(rows);if(insertError)throw insertError; }
async function dashboard(admin: ReturnType<typeof createClient>, userId: string) { await ensureManager(admin,userId);await seedDefaults(admin);const [{data:items,error:itemError},{data:jobs,error:jobError},{data:workers,error:workerError},{data:activity,error:activityError}]=await Promise.all([admin.from("promo_items").select("*").order("due",{ascending:true,nullsFirst:false}).order("id"),admin.from("promo_jobs").select("*").order("approved_at",{ascending:false}),admin.from("promo_workers").select("*").order("last_seen_at",{ascending:false}),admin.from("promo_activity").select("id,item_id,event_type,message,metadata,created_at").order("created_at",{ascending:false}).limit(50)]);if(itemError)throw itemError;if(jobError)throw jobError;if(workerError)throw workerError;if(activityError)throw activityError;return{items:(items??[]).map(mapItem),jobs:(jobs??[]).map(mapJob),workers:(workers??[]).map(mapWorker),activity:(activity??[]).map(row=>({id:row.id,itemId:row.item_id,eventType:row.event_type,message:row.message,metadata:row.metadata,createdAt:row.created_at}))}; }
function normalizedItemPayload(payload: Record<string,any>, current: Record<string,any>) { const status=cleanText(payload.status,20)||current.status;if(!VALID_STATUS.has(status))throw new Error("허용되지 않은 판단 상태입니다.");return{status,content:cleanText(payload.content,60000),notes:cleanText(payload.notes,12000),route:cleanText(payload.route,1000),due:cleanText(payload.due,20)||null,gates:gates(payload.gates),delivery:delivery(payload.delivery)}; }
async function activeJobs(admin: ReturnType<typeof createClient>, itemId: string) { const {data}=await admin.from("promo_jobs").select("id,status,approved_hash").eq("item_id",itemId).in("status",["approved","scheduled","executing","awaiting_automation"]);return data??[]; }
async function activity(admin: ReturnType<typeof createClient>, userId: string|null, itemId: string|null, eventType: string, message: string, metadata: Record<string,unknown>={}) { await admin.from("promo_activity").insert({actor_user_id:userId,item_id:itemId,event_type:eventType,message,metadata}); }

async function managerSave(admin: ReturnType<typeof createClient>, userId: string, payload: Record<string,any>) {
  await ensureManager(admin,userId);const id=cleanText(payload.id,80);const {data:current,error}=await admin.from("promo_items").select("*").eq("id",id).single();if(error||!current)throw new Error("실행항목을 찾지 못했습니다.");const next=normalizedItemPayload(payload,current);const material=next.content!==current.content||next.notes!==current.notes||next.route!==current.route||JSON.stringify(canonical(next.gates))!==JSON.stringify(canonical(current.gates))||JSON.stringify(canonical(next.delivery))!==JSON.stringify(canonical(current.delivery));const active=await activeJobs(admin,id);if(active.length&&(material||["hold","rejected"].includes(next.status))){await admin.from("promo_jobs").update({status:"revoked",result:{status:"revoked",message:"승인 뒤 내용 또는 대표 판단 변경"},finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).in("id",active.map(job=>job.id));next.status=["hold","rejected"].includes(next.status)?next.status:"review";}
  const combined={...current,...next,required_gates:current.required_gates};const ready=isReady(combined,next.gates,next.content,next.route,next.delivery);const engine=next.status==="hold"?{engine_stage:"needs_owner",engine_blocker:"대표가 보류함",engine_next_action:"대표 메모 확인 후 홍보실 재작업"}:next.status==="rejected"?{engine_stage:"stopped",engine_blocker:"대표가 반려함",engine_next_action:"반려 사유가 해소될 때까지 중단"}:next.status==="approved"&&!material?{}:{engine_stage:ready?"ready_for_approval":"queued",engine_blocker:"",engine_next_action:ready?"대표가 최종 문안·수신처 확인 후 실행 승인":nextGate(combined,next.gates),engine_next_run_at:new Date().toISOString(),engine_claimed_by:null,engine_lease_until:null};
  const {error:updateError}=await admin.from("promo_items").update({...next,...engine,approved_hash:next.status==="approved"&&!material?current.approved_hash:null,approved_at:next.status==="approved"&&!material?current.approved_at:null,approved_by:next.status==="approved"&&!material?current.approved_by:null,updated_at:new Date().toISOString()}).eq("id",id);if(updateError)throw updateError;await activity(admin,userId,id,"manager_saved",`${id} ${next.status} 상태로 저장`,{approvalInvalidated:Boolean(active.length&&material),engineStage:engine.engine_stage||current.engine_stage});return{dashboard:await dashboard(admin,userId)};
}
async function managerApprove(admin: ReturnType<typeof createClient>, userId: string, payload: Record<string,any>) {
  await ensureManager(admin,userId);const id=cleanText(payload.id,80);const {data:current,error}=await admin.from("promo_items").select("*").eq("id",id).single();if(error||!current)throw new Error("실행항목을 찾지 못했습니다.");if(current.engine_stage!=="ready_for_approval")throw new Error("홍보실 검증이 끝난 대표 승인 대기 항목만 승인할 수 있습니다.");const next=normalizedItemPayload({...payload,status:"approved"},current);if(!next.content)throw new Error("승인할 최종 문안이 없습니다.");if(!next.route)throw new Error("허용 경로를 확정해 주세요.");const missing=(Array.isArray(current.required_gates)?current.required_gates:[]).filter((key:string)=>next.gates[key]!==true);if(missing.length)throw new Error(`발행 필수조건 ${missing.length}개가 남았습니다.`);const external=!INTERNAL_CATEGORIES.has(current.category);if(external&&!next.delivery.destination)throw new Error("정확한 수신처 또는 공식 게시 URL을 입력해 주세요.");const snapshot={schemaVersion:1,itemId:id,title:current.title,channel:current.channel,category:current.category,risk:current.risk,content:next.content,notes:next.notes,route:next.route,sourceRef:current.source_ref,gates:next.gates,delivery:next.delivery,approvedAt:new Date().toISOString()};const hash=await sha256(snapshot);const active=await activeJobs(admin,id);const same=active.find(job=>job.approved_hash===hash);if(!same&&active.length)await admin.from("promo_jobs").update({status:"revoked",result:{status:"revoked",message:"새 승인본으로 교체"},finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).in("id",active.map(job=>job.id));
  const {error:updateError}=await admin.from("promo_items").update({...next,status:"approved",approved_hash:hash,approved_at:snapshot.approvedAt,approved_by:userId,engine_stage:"approved",engine_last_action:"대표가 실행 승인본을 잠금",engine_next_action:external?"승인본 자동실행":"내부 원칙 적용 완료",engine_blocker:"",engine_last_run_at:new Date().toISOString(),engine_next_run_at:new Date(Date.now()+100*365*24*60*60*1000).toISOString(),engine_claimed_by:null,engine_lease_until:null,updated_at:new Date().toISOString()}).eq("id",id);if(updateError)throw updateError;
  if(external&&!same){const executeAt=next.delivery.scheduledAt;const status=executeAt&&new Date(executeAt).getTime()>Date.now()?"scheduled":"approved";const {error:jobError}=await admin.from("promo_jobs").insert({item_id:id,status,approved_snapshot:snapshot,approved_hash:hash,approved_by:userId,approved_at:snapshot.approvedAt,execute_after:executeAt});if(jobError&&jobError.code!=="23505")throw jobError;}
  await activity(admin,userId,id,"manager_approved",`${id} 실행 승인본 잠금`,{hash:hash.slice(0,16),external,cost:0});return{dashboard:await dashboard(admin,userId)};
}
async function managerRevoke(admin: ReturnType<typeof createClient>, userId: string, payload: Record<string,any>) { await ensureManager(admin,userId);const id=cleanText(payload.id,80);const active=await activeJobs(admin,id);if(active.some(job=>job.status==="executing"))throw new Error("실행 중인 작업입니다. 결과 확인 후 처리해 주세요.");if(active.length)await admin.from("promo_jobs").update({status:"revoked",result:{status:"revoked",message:cleanText(payload.reason,500)||"대표 승인 취소"},finished_at:new Date().toISOString(),updated_at:new Date().toISOString()}).in("id",active.map(job=>job.id));await admin.from("promo_items").update({status:"review",approved_hash:null,approved_at:null,approved_by:null,engine_stage:"ready_for_approval",engine_last_action:"대표가 실행 전 승인을 취소",engine_next_action:"대표 재승인 또는 홍보실 수정 지시 대기",engine_blocker:"",engine_next_run_at:new Date(Date.now()+100*365*24*60*60*1000).toISOString(),engine_claimed_by:null,engine_lease_until:null,updated_at:new Date().toISOString()}).eq("id",id);await activity(admin,userId,id,"manager_revoked",`${id} 실행 전 승인 취소`,{});return{dashboard:await dashboard(admin,userId)}; }

async function workerHeartbeat(admin: ReturnType<typeof createClient>, payload: Record<string,any>) { const workerId=cleanText(payload.workerId,100);if(!workerId)throw new Error("실행기 ID가 필요합니다.");const row={worker_id:workerId,label:cleanText(payload.label,120)||"집 PC 실행기",status:cleanText(payload.status,20)==="attention"?"attention":cleanText(payload.status,20)==="paused"?"paused":"online",version:cleanText(payload.version,80),message:cleanText(payload.message,500),capabilities:cleanTextArray(payload.capabilities,20,80),last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await admin.from("promo_workers").upsert(row,{onConflict:"worker_id"});if(error)throw error;return{ok:true,serverTime:new Date().toISOString()}; }
async function workerClaim(admin: ReturnType<typeof createClient>, payload: Record<string,any>) { const workerId=cleanText(payload.workerId,100);await workerHeartbeat(admin,payload);const now=new Date().toISOString();const expired=new Date(Date.now()-1).toISOString();const {data:stale}=await admin.from("promo_jobs").select("id,status,attempt_count,lease_until").eq("status","executing").lt("lease_until",expired).order("approved_at").limit(1);let candidate=stale?.[0]??null;if(!candidate){const {data}=await admin.from("promo_jobs").select("id,status,attempt_count,lease_until").in("status",["approved","scheduled"]).or(`execute_after.is.null,execute_after.lte.${now}`).order("approved_at").limit(1);candidate=data?.[0]??null;}if(!candidate)return{job:null,serverTime:now};const leaseUntil=new Date(Date.now()+5*60*1000).toISOString();let query=admin.from("promo_jobs").update({status:"executing",claimed_by:workerId,claimed_at:now,lease_until:leaseUntil,attempt_count:Number(candidate.attempt_count||0)+1,updated_at:now}).eq("id",candidate.id).eq("status",candidate.status);if(candidate.status==="executing"&&candidate.lease_until)query=query.eq("lease_until",candidate.lease_until);const {data:claimed,error}=await query.select("*").maybeSingle();if(error)throw error;if(!claimed)return{job:null,serverTime:now};return{job:{id:claimed.id,itemId:claimed.item_id,status:claimed.status,approvedHash:claimed.approved_hash,snapshot:claimed.approved_snapshot,attemptCount:claimed.attempt_count,leaseUntil},serverTime:now}; }
async function workerResult(admin: ReturnType<typeof createClient>, payload: Record<string,any>) { const workerId=cleanText(payload.workerId,100),jobId=cleanText(payload.jobId,100),status=cleanText(payload.status,40);if(!VALID_RESULTS.has(status))throw new Error("허용되지 않은 실행 결과입니다.");const {data:job,error}=await admin.from("promo_jobs").select("id,item_id,claimed_by").eq("id",jobId).single();if(error||!job)throw new Error("실행 작업을 찾지 못했습니다.");if(job.claimed_by!==workerId)throw new Error("이 실행기가 인수한 작업이 아닙니다.");const result={status,message:cleanText(payload.message,2000),externalUrl:cleanText(payload.externalUrl,2000),externalId:cleanText(payload.externalId,500)};const final=status!=="awaiting_automation";const {error:updateError}=await admin.from("promo_jobs").update({status,result,lease_until:null,finished_at:final?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",jobId);if(updateError)throw updateError;await activity(admin,null,job.item_id,"worker_result",`${job.item_id} ${status}`,{workerId,status});return{ok:true}; }

async function workerPreflightClaim(admin: ReturnType<typeof createClient>, payload: Record<string,any>) {
  const workerId=cleanText(payload.workerId,100);if(!workerId)throw new Error("사전승인 실행기 ID가 필요합니다.");await workerHeartbeat(admin,{...payload,capabilities:[...new Set([...cleanTextArray(payload.capabilities,20,80),"preapproval"])]});const now=new Date().toISOString();
  const {data:candidates,error}=await admin.from("promo_items").select("*").in("status",["draft","review","hold"]).in("engine_stage",["queued","drafting","verifying","waiting_external"]).or(`engine_next_run_at.is.null,engine_next_run_at.lte.${now}`).or(`engine_lease_until.is.null,engine_lease_until.lt.${now}`).order("engine_next_run_at",{ascending:true,nullsFirst:true}).order("due",{ascending:true,nullsFirst:false}).order("id").limit(10);if(error)throw error;
  for(const candidate of candidates??[]){const leaseUntil=new Date(Date.now()+10*60*1000).toISOString();const stage=cleanText(candidate.content,60000)?"verifying":"drafting";const {data:claimed,error:claimError}=await admin.from("promo_items").update({status:"review",engine_stage:stage,engine_last_action:"홍보실 자동 작업이 항목을 인수",engine_next_action:stage==="drafting"?"매체별 문안 작성":"남은 발행조건 검증",engine_last_run_at:now,engine_claimed_by:workerId,engine_lease_until:leaseUntil,engine_attempt_count:Number(candidate.engine_attempt_count||0)+1,updated_at:now}).eq("id",candidate.id).eq("engine_attempt_count",Number(candidate.engine_attempt_count||0)).select("*").maybeSingle();if(claimError)throw claimError;if(claimed){await activity(admin,null,claimed.id,"preflight_claimed",`${claimed.id} 사전승인 자동 작업 시작`,{workerId,attempt:claimed.engine_attempt_count});return{item:mapItem(claimed),leaseUntil,serverTime:now};}}
  return{item:null,serverTime:now};
}

async function workerPreflightUpdate(admin: ReturnType<typeof createClient>, payload: Record<string,any>) {
  const workerId=cleanText(payload.workerId,100),id=cleanText(payload.id,80);if(!workerId||!id)throw new Error("사전승인 항목과 실행기 ID가 필요합니다.");const {data:current,error}=await admin.from("promo_items").select("*").eq("id",id).single();if(error||!current)throw new Error("사전승인 항목을 찾지 못했습니다.");if(current.engine_claimed_by!==workerId)throw new Error("이 실행기가 인수한 사전승인 작업이 아닙니다.");if(!["draft","review","hold"].includes(current.status))throw new Error("대표 승인·반려 항목은 자동 수정할 수 없습니다.");
  const has=(key:string)=>Object.prototype.hasOwnProperty.call(payload,key);const nextContent=has("content")?cleanText(payload.content,60000):current.content;const nextNotes=has("notes")?cleanText(payload.notes,12000):current.notes;const nextRoute=has("route")?cleanText(payload.route,1000):current.route;const nextDelivery=has("delivery")?delivery(payload.delivery):delivery(current.delivery);const nextGates={...(current.gates||{}),...(has("gates")?gates(payload.gates):{})};const additions=evidence(payload.evidence);const existing=evidence(current.engine_evidence);const newlyTrue=(Array.isArray(current.required_gates)?current.required_gates:[]).filter((gate:string)=>current.gates?.[gate]!==true&&nextGates[gate]===true);for(const gate of newlyTrue){if(![...existing,...additions].some(entry=>entry.gate===gate))throw new Error(`${GATE_LABELS[gate]||gate} 완료에는 확인 근거가 필요합니다.`);}const mergedEvidence=[...existing,...additions].filter((entry,index,array)=>array.findIndex(other=>other.gate===entry.gate&&other.reference===entry.reference&&other.checkedAt===entry.checkedAt)===index).slice(-80);
  const combined={...current,content:nextContent,notes:nextNotes,route:nextRoute,gates:nextGates,delivery:nextDelivery};const ready=isReady(combined,nextGates,nextContent,nextRoute,nextDelivery);let requested=cleanText(payload.stage,40)||"verifying";if(!VALID_ENGINE_STAGES.has(requested)||["ready_for_approval","approved","stopped"].includes(requested))requested="verifying";const stage=ready?"ready_for_approval":requested;const now=new Date().toISOString();const requestedNext=cleanText(payload.nextRunAt,80);const parsedNext=requestedNext&&Number.isFinite(new Date(requestedNext).getTime())?new Date(requestedNext).toISOString():null;const nextRunAt=ready?new Date(Date.now()+100*365*24*60*60*1000).toISOString():parsedNext||new Date(Date.now()+15*60*1000).toISOString();const nextAction=ready?"대표가 최종 문안·수신처 확인 후 실행 승인":cleanText(payload.nextAction,1000)||nextGate(combined,nextGates);const blocker=cleanText(payload.blocker,1000);
  const {data:updated,error:updateError}=await admin.from("promo_items").update({status:"review",content:nextContent,notes:nextNotes,route:nextRoute,gates:nextGates,delivery:nextDelivery,engine_stage:stage,engine_last_action:cleanText(payload.lastAction,1000)||"홍보실 자동 점검 결과 저장",engine_next_action:nextAction,engine_blocker:blocker,engine_last_run_at:now,engine_next_run_at:nextRunAt,engine_claimed_by:null,engine_lease_until:null,engine_evidence:mergedEvidence,updated_at:now}).eq("id",id).eq("engine_claimed_by",workerId).select("*").single();if(updateError)throw updateError;await activity(admin,null,id,ready?"preflight_ready":"preflight_updated",ready?`${id} 대표 승인 대기 전환`:`${id} 사전승인 점검 갱신`,{workerId,stage,nextAction,evidenceAdded:additions.length});return{ok:true,item:mapItem(updated),readyForApproval:ready};
}

Deno.serve(async (request) => {
  const origin=request.headers.get("Origin");if(request.method==="OPTIONS")return new Response("ok",{headers:cors(origin)});if(request.method!=="POST")return json({error:"Method not allowed"},405,origin);if(origin&&!ALLOWED_ORIGINS.includes(origin))return json({error:"허용되지 않은 접속 위치입니다."},403,origin);
  try{
    const text=await request.text();if(text.length>MAX_REQUEST_CHARS)return json({error:"요청 내용이 허용 범위를 초과했습니다."},413,origin);let body:Record<string,any>;try{body=JSON.parse(text);}catch{return json({error:"요청 형식을 확인해 주세요."},400,origin);}const action=cleanText(body.action,80),payload=body.payload&&typeof body.payload==="object"&&!Array.isArray(body.payload)?body.payload:{};const admin=createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
    const workerKey=request.headers.get("x-promo-worker-key")??"";if(action.startsWith("worker")){if(!sameSecret(workerKey,PROMO_WORKER_KEY))return json({error:"실행기 인증에 실패했습니다."},401,origin);if(action==="workerHeartbeat")return json(await workerHeartbeat(admin,payload),200,origin);if(action==="workerClaim")return json(await workerClaim(admin,payload),200,origin);if(action==="workerResult")return json(await workerResult(admin,payload),200,origin);if(action==="workerPreflightClaim")return json(await workerPreflightClaim(admin,payload),200,origin);if(action==="workerPreflightUpdate")return json(await workerPreflightUpdate(admin,payload),200,origin);return json({error:"지원하지 않는 실행기 작업입니다."},404,origin);}
    const token=bearer(request);if(!token)return json({error:"로그인이 필요합니다."},401,origin);const auth=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{global:{headers:{Authorization:`Bearer ${token}`}}});const {data:userResult,error:userError}=await auth.auth.getUser(token);if(userError||!userResult.user)return json({error:"로그인 시간이 만료되었습니다."},401,origin);const userId=userResult.user.id;
    if(action==="managerDashboard")return json(await dashboard(admin,userId),200,origin);if(action==="managerSave")return json(await managerSave(admin,userId,payload),200,origin);if(action==="managerApprove")return json(await managerApprove(admin,userId,payload),200,origin);if(action==="managerRevoke")return json(await managerRevoke(admin,userId,payload),200,origin);return json({error:"지원하지 않는 작업입니다."},404,origin);
  }catch(error){console.error(error);const detail=error&&typeof error==="object"?error as Record<string,unknown>:{};const message=error instanceof Error?error.message:cleanText(detail.message||detail.details||detail.hint,2000)||"요청을 처리하지 못했습니다.";return json({error:message},400,origin);}
});
