"use strict";

const meta = (name) => document.querySelector(`meta[name="${name}"]`)?.content?.trim() || "";
const config = { supabaseUrl: meta("promo-supabase-url").replace(/\/$/, ""), anonKey: meta("promo-supabase-anon-key") };
config.production = Boolean(config.supabaseUrl && config.anonKey);
const localDemoAllowed = ["127.0.0.1", "localhost"].includes(location.hostname) && new URLSearchParams(location.search).get("demo") === "1";
const AUTH_STORAGE_KEY = "sugar-salt-review-auth-v1";
const AUTH_MAX_AGE_MS = 14 * 24 * 60 * 60 * 1000;
const AUTO_REFRESH_MS = 30000;
const $ = (selector, root = document) => root.querySelector(selector);
const INTERNAL_CATEGORIES = new Set(["비용통제", "핵심자산", "조사", "통제"]);
const state = { mode: "demo", token: null, refreshToken: null, tokenExpiresAt: 0, refreshPromise: null, remember: true, items: [], jobs: [], workers: [], activity: [], selectedId: null, loading: false, lastSyncedAt: null, timer: null };

const gateCopy = {
  fact: ["사실 근거", "수치·이력·완료 표현을 원본과 대조"],
  review: ["외부 전공검토", "동의받은 범위·기준·날짜 확인, 개인 신상 비공개"],
  product: ["무료 전문·상품 링크", "4과목 대표 단원과 모의고사 1회 공개 범위 확인"],
  disclosure: ["관계·비용 없음 표시", "회사 공식 홍보와 비용·협찬 없음 표시"],
  rules: ["매체 규정", "최신 규정 확인 또는 운영자 서면 허가"],
  utm: ["추적 링크", "매체·문안별 링크와 정상 접속 확인"],
  privacy: ["개인정보 비식별화", "대표 본인·회사 공식정보 외 제3자 정보 제거"]
};
const statusCopy = { draft: "초안", review: "검토중", approved: "승인", hold: "보류", rejected: "반려" };
const jobCopy = { approved: "실행 대기", scheduled: "예약됨", executing: "실행 중", awaiting_automation: "자동화 대기", sent: "발송 완료", published: "게시 완료", failed: "실패", needs_attention: "대표 확인", rejected_by_platform: "플랫폼 거절", revoked: "승인 취소" };

const DEMO_ITEMS = [
  { id:"PR-01", title:"전국 무료제보용 표준 보도자료", channel:"언론사 공식 제보창구", category:"언론", due:"2026-08-17", status:"review", risk:"중", sourceRef:"매체별_기사보도자료_완성본_v1.md §2", notes:"유료 배포서비스 제외. 사실과 무료범위를 최종 대조합니다.", content:"광고비 대신 검토 과정과 무료 원문을 공개한 작은 교육회사의 실험이 시작됐습니다.\n\n헌법·행정법·행정학·경제학의 대표 단원과 모의고사 1회 전체를 로그인 없이 공개합니다. 외부 전공 전문가 검토 후 AI가 오류 후보를 교차 점검하고 최종 판단은 사람이 담당합니다.", route:"공식 무료 제보창구", requiredGates:["fact","review","product","disclosure","rules","utm","privacy"], gates:{fact:true,review:true,product:false,disclosure:true,rules:true,utm:false,privacy:true}, delivery:{adapter:"email_connector",destination:"",scheduledAt:"",attachments:[],cost:0} },
  { id:"PR-02", title:"이로운넷 사회적 가치 기사안", channel:"이로운넷", category:"언론", due:"2026-08-16", status:"review", risk:"중", sourceRef:"매체별_기사보도자료_완성본_v1.md §3", notes:"협의된 범위만 사용합니다.", content:"정보 접근 격차를 줄이는 무료 수험자료 공개 실험을 제안합니다. 검증 절차와 무료 공개 범위를 사실 중심으로 설명합니다.", route:"담당 기자 맞춤 피치", requiredGates:["fact","review","product","disclosure","rules","utm","privacy"], gates:{fact:true,review:false,product:false,disclosure:true,rules:true,utm:false,privacy:true}, delivery:{adapter:"email_connector",destination:"",scheduledAt:"",attachments:[],cost:0} },
  { id:"CM-04", title:"블라인드 직접홍보·제작자 공개형 도전", channel:"블라인드 직접 홍보", category:"직접홍보", due:"2026-08-17", status:"review", risk:"중", sourceRef:"커뮤니티_확장운영안_v1.md §5-G", notes:"첫 두 문장에 대표·제작자 관계 표시.", content:"유한회사 설탕과소금 공직시험연구소를 운영하며 자료 제작에 참여한 대표입니다. 먼저 믿어 달라는 말 대신 4과목 대표 단원과 모의고사 1회분 전체를 로그인 없이 열었습니다.\n\n무료분만 보고 냉정하게 평가해 주시면 좋겠습니다. 이 글은 제작자인 제가 직접 올리는 홍보 글이며 게시·소개 대가는 없습니다.", route:"대표·제작자 관계 공개형 글", requiredGates:["fact","product","disclosure","rules","utm","privacy"], gates:{fact:true,product:false,disclosure:true,rules:false,utm:false,privacy:true}, delivery:{adapter:"browser",destination:"",scheduledAt:"",attachments:[],cost:0} },
  { id:"COST-01", title:"유료홍보 0원·운영경비 3단계 승인", channel:"전체", category:"비용통제", due:"", status:"approved", risk:"낮음", sourceRef:"무광고_수작업홍보_비용승인원칙.md", notes:"광고·유료기사·유료배포·유료게시·협찬·수수료는 집행하지 않습니다.", content:"유료홍보 집행액은 0원으로 고정합니다.", route:"원칙 상시 적용", requiredGates:["rules","privacy"], gates:{rules:true,privacy:true}, delivery:{adapter:"browser",destination:"",scheduledAt:"",attachments:[],cost:0} }
];

function escapeHtml(value="") { return String(value ?? "").replace(/[&<>"']/g, (character) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]); }
function toast(message) { const element=$("#toast"); element.textContent=message; element.classList.add("show"); clearTimeout(toast.timer); toast.timer=setTimeout(()=>element.classList.remove("show"),2800); }
function readPersistedSession(){try{const saved=JSON.parse(localStorage.getItem(AUTH_STORAGE_KEY)||"null");if(!saved?.refreshToken||Date.now()-Number(saved.savedAt||0)>AUTH_MAX_AGE_MS)return null;return saved;}catch{return null;}}
function persistSession(){if(!state.remember||!state.refreshToken)return;localStorage.setItem(AUTH_STORAGE_KEY,JSON.stringify({accessToken:state.token,refreshToken:state.refreshToken,expiresAt:state.tokenExpiresAt,savedAt:Date.now()}));}
function applySession(session){state.token=session.access_token;if(session.refresh_token)state.refreshToken=session.refresh_token;state.tokenExpiresAt=Date.now()+Math.max(60,Number(session.expires_in)||3600)*1000;persistSession();}
function clearSession(){localStorage.removeItem(AUTH_STORAGE_KEY);state.token=null;state.refreshToken=null;state.tokenExpiresAt=0;}
async function refreshSession(){if(!state.refreshToken)throw new Error("로그인 시간이 만료되었습니다.");if(state.refreshPromise)return state.refreshPromise;state.refreshPromise=(async()=>{const response=await fetch(`${config.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey},body:JSON.stringify({refresh_token:state.refreshToken}),cache:"no-store",credentials:"omit"});const body=await response.json().catch(()=>({}));if(!response.ok||!body.access_token){clearSession();throw new Error("다시 로그인해 주세요.");}applySession(body);})();try{await state.refreshPromise;}finally{state.refreshPromise=null;}}
async function api(action,payload={},retried=false){if(state.refreshToken&&Date.now()>=state.tokenExpiresAt-60000)await refreshSession();const response=await fetch(`${config.supabaseUrl}/functions/v1/promo-control`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey,Authorization:`Bearer ${state.token}`},body:JSON.stringify({action,payload}),cache:"no-store",credentials:"omit"});const body=await response.json().catch(()=>({}));if(response.status===401&&!retried&&state.refreshToken){await refreshSession();return api(action,payload,true);}if(!response.ok)throw new Error(body.error||"요청을 처리하지 못했습니다.");return body;}
async function sendOtp(email){const response=await fetch(`${config.supabaseUrl}/auth/v1/otp`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey},body:JSON.stringify({email,create_user:false,email_redirect_to:`${location.origin}${location.pathname}`}),cache:"no-store"});if(!response.ok)throw new Error("등록된 회사 관리자 이메일인지 확인해 주세요.");}
async function verifyOtp(email,token){const response=await fetch(`${config.supabaseUrl}/auth/v1/verify`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.anonKey},body:JSON.stringify({email,token,type:"email"}),cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok||!body.access_token)throw new Error(body.error_description||"인증번호를 확인해 주세요.");return body;}
function magicLinkSession(){if(!location.hash)return null;const params=new URLSearchParams(location.hash.slice(1));history.replaceState(null,"",`${location.pathname}${location.search}`);if(params.get("error_description"))throw new Error(params.get("error_description"));if(!params.get("access_token"))return null;return{access_token:params.get("access_token"),refresh_token:params.get("refresh_token")||"",expires_in:Number(params.get("expires_in"))||3600};}

function isExternal(item){return !INTERNAL_CATEGORIES.has(item.category);}
function latestJob(itemId){return state.jobs.find(job=>job.itemId===itemId)||null;}
function missingGates(item){return (item.requiredGates||[]).filter(gate=>item.gates?.[gate]!==true);}
function formatDate(value){if(!value)return"기록 없음";return new Intl.DateTimeFormat("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));}
function jobBadge(job){if(!job)return'<span class="badge draft">승인 전</span>';const status=job.status;const klass=["sent","published"].includes(status)?"done":["failed","needs_attention","rejected_by_platform"].includes(status)?"attention":status==="revoked"?"rejected":"queued";return `<span class="badge ${klass}">${escapeHtml(jobCopy[status]||status)}</span>`;}
function updateMetrics(){const activeJobs=state.jobs.filter(j=>!["revoked"].includes(j.status));$("#metric-total").textContent=state.items.length;$("#metric-review").textContent=state.items.filter(i=>["draft","review"].includes(i.status)).length;$("#metric-queued").textContent=activeJobs.filter(j=>["approved","scheduled","executing","awaiting_automation"].includes(j.status)).length;$("#metric-done").textContent=activeJobs.filter(j=>["sent","published"].includes(j.status)).length;$("#metric-attention").textContent=activeJobs.filter(j=>["failed","needs_attention","rejected_by_platform"].includes(j.status)).length;}
function updateWorker(){const worker=state.workers[0];const panel=$("#worker-status");panel.className="worker-status";if(!worker){$("#worker-title").textContent="집 PC 실행기 연결 대기";$("#worker-copy").textContent="클라우드 배포 후 집 PC에 실행기 키를 연결하면 자동 수신을 시작합니다.";return;}const age=Date.now()-new Date(worker.lastSeenAt).getTime();if(age<120000&&worker.status!=="attention"){panel.classList.add("online");$("#worker-title").textContent="집 PC 실행기 온라인";$("#worker-copy").textContent=`최근 확인 ${formatDate(worker.lastSeenAt)} · ${worker.version||"버전 미기록"}`;}else{panel.classList.add("attention");$("#worker-title").textContent="집 PC 실행기 확인 필요";$("#worker-copy").textContent=`마지막 연결 ${formatDate(worker.lastSeenAt)} · 승인 기록은 안전하게 대기합니다.`;}}
function filteredItems(){const category=$("#category").value,status=$("#status").value,query=$("#query").value.trim().toLowerCase();return state.items.filter(item=>(!category||item.category===category)&&(!status||item.status===status)&&(!query||[item.id,item.title,item.channel,item.route,item.sourceRef].join(" ").toLowerCase().includes(query)));}
function renderQueue(){const items=filteredItems();$("#result-count").textContent=`${items.length}건`;$("#empty").hidden=items.length>0;$("#queue").innerHTML=items.map(item=>{const job=latestJob(item.id),missing=missingGates(item);return `<button class="queue-item" type="button" data-item-id="${escapeHtml(item.id)}"><span class="queue-title"><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.id)} · ${escapeHtml(item.channel)}</small></span><span class="queue-meta"><span>${escapeHtml(item.route||"허용경로 확인 중")}</span><small>${escapeHtml(item.category)}</small></span><span class="badge ${escapeHtml(item.status)}">${escapeHtml(statusCopy[item.status]||item.status)}</span>${jobBadge(job)}<span class="queue-meta"><span>${missing.length?`조건 ${missing.length}개 남음`:"조건 완료"}</span><small>${item.due?`목표 ${escapeHtml(item.due)}`:"상시"}</small></span><span class="queue-arrow">›</span></button>`;}).join("");}
function render(){updateMetrics();updateWorker();const categories=[...new Set(state.items.map(item=>item.category))];const current=$("#category").value;$("#category").innerHTML='<option value="">전체 채널</option>'+categories.map(value=>`<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`).join("");$("#category").value=categories.includes(current)?current:"";renderQueue();}
function enter(result){state.items=result.items||[];state.jobs=result.jobs||[];state.workers=result.workers||[];state.activity=result.activity||[];state.lastSyncedAt=new Date().toISOString();$("#login").hidden=true;$("#app").hidden=false;render();setSync("",`자동 갱신 30초 · ${formatDate(state.lastSyncedAt)}`);schedule();}
function setSync(kind,message){const el=$("#sync");el.className=`sync ${kind}`.trim();el.querySelector("span").textContent=message;}
function schedule(){clearTimeout(state.timer);if(state.mode==="production")state.timer=setTimeout(()=>loadDashboard(true).catch(()=>{}),AUTO_REFRESH_MS);}
async function loadDashboard(automatic=false){if(state.loading)return;state.loading=true;setSync("loading","서버 기록 갱신 중…");try{const result=await api("managerDashboard");enter(result);}catch(error){setSync("error",automatic?"자동 갱신 실패 · 다시 시도 중":"서버 확인 실패");if(!automatic)throw error;}finally{state.loading=false;schedule();}}

function selectedItem(){return state.items.find(item=>item.id===state.selectedId);}
function valuePayload(status){const item=selectedItem();return{id:item.id,status,content:$("#content").value.trim(),notes:$("#notes").value.trim(),route:$("#route").value.trim(),due:$("#due").value||null,gates:Object.fromEntries([...$("#gate-list").querySelectorAll("input[data-gate]")].map(input=>[input.dataset.gate,input.checked])),delivery:{adapter:$("#adapter").value,destination:$("#destination").value.trim(),scheduledAt:$("#execute-at").value?new Date($("#execute-at").value).toISOString():null,attachments:$("#attachments").value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean),cost:0}};}
function openDetail(id){const item=state.items.find(value=>value.id===id);if(!item)return;state.selectedId=id;const job=latestJob(id),missing=missingGates(item);$("#detail-category").textContent=`${item.category} · ${item.channel}`;$("#detail-title").textContent=item.title;$("#detail-badges").innerHTML=`<span class="badge ${item.status}">${escapeHtml(statusCopy[item.status]||item.status)}</span><span class="badge ${item.risk==="상"?"attention":item.risk==="중"?"queued":"approved"}">위험 ${escapeHtml(item.risk)}</span>${jobBadge(job)}`;$("#content").value=item.content||"";$("#notes").value=item.notes||"";$("#route").value=item.route||"";$("#destination").value=item.delivery?.destination||"";$("#adapter").value=item.delivery?.adapter||"browser";$("#execute-at").value=item.delivery?.scheduledAt?new Date(item.delivery.scheduledAt).toISOString().slice(0,16):"";$("#attachments").value=(item.delivery?.attachments||[]).join("\n");$("#due").value=item.due||"";$("#source-ref").textContent=item.sourceRef||"근거 문서 확인 필요";$("#gate-list").innerHTML=(item.requiredGates||[]).map(key=>{const copy=gateCopy[key]||[key,"확인 필요"];return `<label><input type="checkbox" data-gate="${escapeHtml(key)}" ${item.gates?.[key]?"checked":""}><span><b>${escapeHtml(copy[0])}</b><small>${escapeHtml(copy[1])}</small></span></label>`;}).join("");$("#gate-count").textContent=missing.length?`${missing.length}개 남음`:"모두 완료";$("#next-title").textContent=missing.length?`${gateCopy[missing[0]]?.[0]||missing[0]}부터 완료`:job?jobCopy[job.status]||job.status:"대표 승인 가능";$("#next-copy").textContent=missing.length?"홍보실이 남은 근거와 규정을 확인한 뒤 대표 승인 대기 상태로 다시 올립니다.":job?.result?.message||"문안과 정확한 수신처를 확인하면 승인본이 잠기고 실행기가 자동 처리합니다.";$("#confirm").checked=false;$("#approve").disabled=true;$("#revoke").hidden=!job||!["approved","scheduled","executing","awaiting_automation"].includes(job.status);$("#detail").showModal();}
async function mutate(action,payload,success){try{const result=state.mode==="production"?await api(action,payload):demoMutate(action,payload);enter(result.dashboard||result);$("#detail").close();toast(success);}catch(error){toast(error.message);}}
function demoMutate(action,payload){const item=state.items.find(value=>value.id===payload.id);if(!item)throw new Error("항목을 찾지 못했습니다.");if(action==="managerApprove"){const missing=(item.requiredGates||[]).filter(key=>payload.gates?.[key]!==true);if(missing.length)throw new Error(`필수조건 ${missing.length}개를 먼저 완료해 주세요.`);if(isExternal(item)&&!payload.delivery?.destination)throw new Error("정확한 수신처 또는 공식 게시 URL이 필요합니다.");Object.assign(item,payload,{status:"approved"});if(isExternal(item))state.jobs.unshift({id:`demo-${Date.now()}`,itemId:item.id,status:"approved",approvedAt:new Date().toISOString(),result:null});}else if(action==="managerSave"){Object.assign(item,payload);}else if(action==="managerRevoke"){const job=latestJob(item.id);if(job)job.status="revoked";item.status="review";}return{dashboard:{items:state.items,jobs:state.jobs,workers:state.workers,activity:state.activity}};}

$("#login-form").addEventListener("submit",async event=>{event.preventDefault();if(!config.production){toast("로컬 확인은 체험 버튼을 이용해 주세요.");return;}try{await sendOtp($("#email").value.trim());$("#otp-row").hidden=false;$("#otp").focus();toast("관리자 이메일로 인증번호를 보냈습니다.");}catch(error){toast(error.message);}});
$("#otp-submit").addEventListener("click",async()=>{try{state.remember=$("#remember").checked;applySession(await verifyOtp($("#email").value.trim(),$("#otp").value.trim()));state.mode="production";await loadDashboard();}catch(error){toast(error.message);}});
$("#demo").addEventListener("click",()=>{state.mode="demo";enter({items:structuredClone(DEMO_ITEMS),jobs:[],workers:[],activity:[]});});
$("#logout").addEventListener("click",()=>{const token=state.token;clearSession();if(token)fetch(`${config.supabaseUrl}/auth/v1/logout`,{method:"POST",headers:{apikey:config.anonKey,Authorization:`Bearer ${token}`}}).catch(()=>{});location.href=location.pathname;});
$("#refresh").addEventListener("click",()=>state.mode==="production"?loadDashboard().catch(error=>toast(error.message)):(state.lastSyncedAt=new Date().toISOString(),setSync("",`체험 갱신 · ${formatDate(state.lastSyncedAt)}`)));
[$("#category"),$("#status")].forEach(el=>el.addEventListener("change",renderQueue));$("#query").addEventListener("input",renderQueue);$("#queue").addEventListener("click",event=>{const item=event.target.closest("[data-item-id]");if(item)openDetail(item.dataset.itemId);});
[$("#content"),$("#route"),$("#destination"),$("#adapter"),$("#execute-at"),$("#attachments"),$("#due"),$("#gate-list")].forEach(el=>el.addEventListener("input",()=>{$("#confirm").checked=false;$("#approve").disabled=true;}));
$("#confirm").addEventListener("change",event=>$("#approve").disabled=!event.target.checked);
$("#save").addEventListener("click",()=>mutate("managerSave",valuePayload(selectedItem().status),"변경 내용을 안전하게 저장했습니다."));
$("#hold").addEventListener("click",()=>mutate("managerSave",valuePayload("hold"),"대표 보류로 저장했습니다."));
$("#reject").addEventListener("click",()=>mutate("managerSave",valuePayload("rejected"),"현재 문안을 반려했습니다. 대상 수험생층을 유지한 대체 문안은 별도 검토합니다."));
$("#approve").addEventListener("click",()=>mutate("managerApprove",valuePayload("approved"),"승인본을 잠갔습니다. 집 PC 실행기가 자동 처리합니다."));
$("#revoke").addEventListener("click",()=>mutate("managerRevoke",{id:selectedItem().id,reason:"대표가 실행 전 승인을 취소함"},"외부 실행 전 승인을 취소했습니다."));
$("#worker-help").addEventListener("click",()=>{const worker=state.workers[0];$("#worker-detail").innerHTML=worker?[ ["실행기",worker.label||worker.workerId],["상태",worker.status],["마지막 연결",formatDate(worker.lastSeenAt)],["버전",worker.version||"미기록"],["최근 메시지",worker.message||"정상"] ].map(([a,b])=>`<article><span>${escapeHtml(a)}</span><strong>${escapeHtml(b)}</strong></article>`).join(""):'<article><span>상태</span><strong>아직 연결되지 않았습니다. 배포 후 집 PC에 비밀 실행기 키를 1회 설정하면 됩니다.</strong></article>';$("#worker-dialog").showModal();});

if(config.production&&!localDemoAllowed){$("#demo").hidden=true;(async()=>{try{const magic=magicLinkSession();if(magic){applySession(magic);state.mode="production";await loadDashboard();return;}const saved=readPersistedSession();if(saved){state.token=saved.accessToken;state.refreshToken=saved.refreshToken;state.tokenExpiresAt=Number(saved.expiresAt||0);state.remember=true;if(!state.token||Date.now()>=state.tokenExpiresAt-60000)await refreshSession();state.mode="production";await loadDashboard();}}catch(error){clearSession();toast(error.message);}})();}
