import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const checks = [];
const check = (name, condition, detail) => checks.push({ name, condition: Boolean(condition), detail });

const html = read("review/index.html");
const css = read("review/review.css");
const js = read("review/review.js");
const sql = read("review/supabase/review-room-schema.sql");
const edge = read("review/supabase/functions/review-content/index.ts");
const deploymentEdge = read("supabase/functions/review-content/index.ts");
const normalizeLineEndings = (value) => value.replace(/\r\n/g, "\n");
const headers = read("review/_headers");
const managerHtml = read("review/manage.html");
const managerJs = read("review/manage.js");
const batchSql = read("review/supabase/migrations/20260812000000_review_batch_start.sql");
const historySql = read("review/supabase/migrations/20260813000000_review_change_history.sql");
const nationalSubjectSql = read("review/supabase/migrations/20260813010000_fix_national_subject_names.sql");
const runtimeControlSql = read("review/supabase/migrations/20260814000000_review_runtime_controls.sql");
const reportWorkflowSql = read("review/supabase/migrations/20260814010000_review_report_workflow.sql");
const integritySql = read("review/supabase/migrations/20260814020000_review_integrity_tracking.sql");
const notificationArchiveSql = read("review/supabase/migrations/20260814040000_review_notification_archive.sql");
const migrationDirectory = path.join(root, "review/supabase/migrations");
const migrationFiles = fs.readdirSync(migrationDirectory).sort();
const migrations = migrationFiles.map((file) => read(`review/supabase/migrations/${file}`)).join("\n");
const productionInfrastructureVerifier = read("tools/verify_review_production_project.mjs");

check("page.noindex", html.includes('name="robots" content="noindex, nofollow, noarchive, nosnippet"'), "보호 페이지가 검색에 노출되지 않습니다.");
check("page.programs", ["국가직 7급 공무원시험 대비", "초등교원임용고사 대비", "중등교원임용고사 대비"].every((value) => js.includes(value)), "세 시험군이 하나의 워크룸 구조에 포함됩니다.");
check("tools.annotation", ["형광펜", "전문 의견", "수정 필요"].every((value) => html.includes(value)), "핵심 검수 도구가 존중 표현으로 제공됩니다.");
check("tools.selection-popover", html.includes("selection-popover") && js.includes("showSelectionPopover") && js.includes('(pointer: coarse)'), "선택 즉시 PC 위쪽·터치 기기 아래쪽에 검수 도구가 표시됩니다.");
check("tools.mobile-layout", css.includes("data-short") && css.includes("max-width: calc(100vw - 16px)") && css.includes("grid-template-columns: 1fr;"), "스마트폰에서도 헤더·제출 버튼·원고가 화면 폭 안에서 정돈됩니다.");
check("tools.ipad-scroll", css.includes("-webkit-overflow-scrolling: touch") && css.includes("touch-action: pan-y") && css.includes("calc(100dvh - 155px)"), "아이패드에서도 원고 영역이 화면 높이에 맞춰 즉시 터치 스크롤됩니다.");
check("tools.large-review", html.includes("큰 화면 검수") && html.includes("기본 화면으로") && html.includes('aria-pressed="false"') && js.includes("setFocusMode") && js.includes("readerBaseFontSize") && css.includes("body.focus-mode .app-header") && css.includes("display: none !important") && css.includes("grid-template-columns: minmax(0, 1fr)") && css.includes("width: calc(100% - 56px)"), "큰화면 검수에서는 일반 메뉴와 좌우 패널을 숨기고 원고와 검수 도구만 화면 가득 표시하며 명확한 기본 화면 복귀 버튼을 제공합니다.");
check("tools.autosave", js.includes("scheduleSave") && js.includes("saveRetryCounts") && js.includes("저장 재시도 중") && js.includes('window.addEventListener("online"') && html.includes("자동으로 저장"), "문단 확인과 전체 의견을 자동저장하고 연결 장애 뒤 자동 재시도합니다.");
check("content.source-tables", js.includes("REVIEW_TABLE_V1") && js.includes("renderTableGroup") && css.includes("review-data-table") && css.includes("review-table-confirm"), "원본 표를 셀별 문장으로 흩뜨리지 않고 전문 검수용 표로 복원합니다.");
check("content.table-progress", js.includes("data-check-blocks") && js.includes("toggleBlocks") && js.includes("review-table-cell"), "표의 행 확인과 셀별 검수 의견이 기존 진행기록·보고서에 연결됩니다.");
check("auth.remembered-session", js.includes("AUTH_MAX_AGE_MS") && managerJs.includes("AUTH_MAX_AGE_MS") && html.includes("14일간 인증 상태 유지") && managerHtml.includes("14일간 관리자 인증 유지"), "기기별 14일 인증 유지와 명시적 로그아웃을 제공합니다.");
check("auth.otp-length-neutral", html.includes("이메일로 받은 인증번호") && !html.includes("6자리 인증번호"), "인증번호 자릿수가 운영 설정과 달라도 전문위원님께 잘못된 안내를 하지 않습니다.");
check("auth.operational-email-route", js.includes('action: "requestOtp"') && managerJs.includes('action:"requestOtp"') && !js.includes("/auth/v1/otp") && !managerJs.includes("/auth/v1/otp") && edge.includes('action === "requestOtp"') && edge.includes("admin.auth.admin.generateLink") && edge.includes("buildOtpEmailHtml") && edge.includes("sendOperationalEmail"), "인증번호는 Supabase 내장 시험메일이 아니라 운영 메일 공급자를 통해 발송합니다.");
check("auth.rate-limit-and-enumeration", edge.includes("OTP_COOLDOWN_MS") && edge.includes("OTP_WINDOW_LIMIT") && edge.includes("OTP_DAILY_LIMIT") && edge.includes("auth_otp_rate_limited") && edge.includes("등록된 이메일이면 인증번호 안내가 발송됩니다") && edge.includes("clientIpHash") && edge.includes('.in("status", ["assigned", "reviewing", "submitted", "returned", "accepted"])'), "인증번호 남용을 제한하고 미등록·미개시 계정 여부를 응답으로 노출하지 않습니다.");
check("auth.audit-trail", ["auth_otp_requested", "auth_otp_sent", "auth_otp_failed", "auth_login_succeeded"].every((value) => edge.includes(value)) && edge.includes("otpRequestedAt") && edge.includes("otpSentAt") && edge.includes("loginSucceededAt") && managerJs.includes("인증메일 운영 발송"), "인증 요청·운영메일 접수·로그인 성공·실패를 관리자 관제에서 분리 확인합니다.");
check("deployment.edge-source-parity", normalizeLineEndings(edge) === normalizeLineEndings(deploymentEdge), "검증 대상 함수와 저장소 루트에서 실제 CLI로 배포되는 함수가 완전히 동일합니다.");
check("deployment.review-asset-version", html.includes("review.js?v=20260815-2") && managerHtml.includes("manage.js?v=20260815-2"), "일반 새로고침만으로도 전문위원·관리자 화면이 최신 검수 코드를 받습니다.");
check("language.respect", html.includes("전문위원님") && js.includes("귀한 검토에 감사드립니다") && !html.includes("외부 검수자"), "전문위원 화면의 기본 호칭과 안내가 존중 표현을 사용합니다.");
check("report.standard-file", html.includes("download-review-report") && js.includes("sugar-salt-expert-review/v1") && js.includes("교재 생성 시스템 인계 규칙"), "검수위원 인적사항과 의견을 표준 보고서 파일로 생성합니다.");
check("report.preview-edit", html.includes("report-preview-dialog") && js.includes("원문에서 보완") && js.includes("data-report-document"), "보고서 미리보기에서 해당 원문 의견으로 돌아가 수정할 수 있습니다.");
check("report.human-format", html.includes("공식 검수보고서 미리보기·보완") && js.includes("humanReportMarkup") && js.includes("printableReportHtml") && !html.includes("report-preview-raw"), "사람이 읽는 미리보기와 저장 파일은 원시 YAML 대신 공식 보고서 양식을 사용합니다.");
check("review.integrity-tracking", integritySql.includes("review_block_checks") && edge.includes('action === "recordBlockViews"') && edge.includes('action === "recordBlockChecks"') && js.includes("IntersectionObserver"), "문단 노출과 확인 시각을 서버 기준으로 기록합니다.");
check("review.integrity-request-dedup", js.includes("queuedBlockViews") && js.includes("recordedBlockViews") && js.includes("remoteDocumentPromises"), "화면 재렌더링과 연속 선택에서도 동일 열람기록·원고 요청을 중복 전송하지 않습니다.");
check("review.document-prefetch", js.includes("prefetchAdjacentDocuments") && js.includes("requestIdleCallback") && js.includes("flushPendingSaves().catch"), "인접 원고를 유휴 시간에 미리 불러오고 자동저장이 화면 전환을 막지 않습니다.");
check("api.parallel-document-load", edge.includes("Promise.all([") && edge.includes("documentResult, blockResult, annotationResult, progressResult"), "원고·문단·의견·진행기록을 병렬 조회하여 챕터 전환 대기를 줄입니다.");
check("review.integrity-threshold", edge.includes("reviewReadingEstimate") && edge.includes("estimatedSeconds * 0.35") && edge.includes('return "bulk"'), "초고속·일괄 확인을 보수적인 내부 기준으로 분류합니다.");
check("review.integrity-presubmit", html.includes("submission-integrity-dialog") && js.includes("getSubmissionIntegrity") && html.includes("대표 보고서에 그대로 포함"), "최종 제출 전에 미확인·속도 주의기록과 대표 보고 사실을 전문위원에게 표시합니다.");
check("review.integrity-override", edge.includes("integrityAcknowledged") && edge.includes("submission_integrity_acknowledged") && js.includes("confirmAssignmentSubmission"), "전문위원이 주의기록을 명시적으로 확인한 경우에만 해당 기록을 포함해 제출을 계속할 수 있습니다.");
check("manager.integrity-report", managerJs.includes("managerIntegrityMarkup") && edge.includes("reviewIntegrity") && edge.includes("검수완전성 원기록"), "대표 보고서·AI 보조검토·Claude Code 인계자료에 동일한 검수완전성 원기록을 포함합니다.");
check("manager.report-approval", managerHtml.includes("대표 검토·승인") && managerJs.includes("managerApproveReport") && edge.includes('action === "managerApproveReport"') && reportWorkflowSql.includes("review_manager_reviews"), "전문위원 원문을 보존한 채 대표 검토·승인 기록을 별도 보관합니다.");
check("manager.ai-supplement", managerHtml.includes("AI 보조검토") && managerJs.includes("managerAiMarkup") && edge.includes("buildAiSupplement") && edge.includes("전문위원의 학문적 판단"), "AI 의견은 누락·우선순위 보조분석으로 분리하고 전문위원 판단을 대체하지 않습니다.");
check("manager.claude-handoff-gate", managerHtml.includes("Claude Code 인계자료") && managerJs.includes("downloadHandoffPackage") && edge.includes('action === "managerGetHandoffPackage"') && edge.includes('managerReview?.status !== "approved"'), "대표 승인 전에는 Claude Code 인계자료가 생성되지 않습니다.");
check("manager.report-source-link", managerJs.includes("data-manager-source-document") && js.includes("managerPreviewDocumentId") && js.includes("managerPreviewFindingId"), "대표 검토 화면에서 전문위원 의견의 원문 위치로 이동할 수 있습니다.");
check("report.receipt", html.includes("report-receipt") && edge.includes("deliveryStatus") && js.includes("교재 제작 시스템 전달 완료"), "제출 접수와 관리자 인계 상태를 전문위원 화면에 지속 표시합니다.");
check("manager.actual-progress", managerHtml.includes("실제 문단 확인률") || managerHtml.includes("실제 문단 확인") && managerJs.includes("checkedBlocks") && managerJs.includes("completeDocumentCount"), "운영관제가 자기보고가 아닌 서버 기록으로 실제 진도를 계산합니다.");
check("manager.activity-source-separation", edge.includes('from("review_block_checks")') && edge.includes("viewedBlocks") && managerJs.includes("화면 노출") && managerJs.includes("첫 검수 확인·의견"), "원고 화면 노출과 실제 확인·전문 의견을 분리하여 관제합니다.");
check("manager.inactivity-24h", edge.includes("24 * 60 * 60 * 1000") && edge.includes("24시간 인증·접속 기록 없음") && edge.includes("연락 전 시스템 기록 확인"), "24시간 무활동은 서버 원기록 확인을 전제로 주의 표시합니다.");
check("manager.handoff-stages", ["최종 제출", "보고서 생성", "인계 완료"].every((value) => managerJs.includes(value)) && managerJs.includes("markReportDelivered"), "최종 제출부터 보고서 전달까지 단계별로 관리합니다.");
check("manager.access-control", edge.includes("ensureManager") && edge.includes('action === "managerDashboard"') && edge.includes('action === "managerGetReport"'), "운영관제와 보고서 열람은 회사 관리자 권한으로 제한됩니다.");
check("manager.readonly-preview", managerHtml.includes("preview-assignment") && managerJs.includes("managerPreview") && edge.includes('action === "managerPreviewBootstrap"') && edge.includes('action === "managerPreviewDocument"') && edge.includes('action === "managerPreviewReport"'), "admin 계정이 전문위원 실제 화면과 보고서를 읽기 전용으로 확인합니다.");
check("manager.expert-registration", managerHtml.includes("expert-form") && edge.includes('action === "managerUpsertExpert"') && edge.includes("admin.createUser") && edge.includes("invitationSent: false"), "전문위원 정보는 내부 등록되며 일괄 시작 전에는 초대 메일이 발송되지 않습니다.");
check("manager.expert-directory", managerHtml.includes("expert-directory-dialog") && managerJs.includes("renderExpertDirectory") && managerJs.includes("summary-registered"), "등록 전문위원 전체 명단과 위촉 현황을 별도로 집계합니다.");
check("manager.subject-assignment", managerHtml.includes("assignment-form") && edge.includes('action === "managerSaveAssignment"') && edge.includes("review_assignment_documents"), "과목·검수 자료·기간 위촉을 운영관제에서 설정합니다.");
check("manager.national-subject-names", managerJs.includes('name:"국가직 7급 공무원시험 대비"') && ["헌법", "행정법", "행정학", "경제학"].every((value) => managerJs.includes(`name:\"${value}\"`)) && !managerJs.includes('name:"행정법총론"') && !managerJs.includes('name:"행정학개론"') && !managerJs.includes('name:"경제학원론"') && nationalSubjectSql.includes("'[국가직 7급] 행정법'") && nationalSubjectSql.includes("'국가직 7급 공무원시험 대비'"), "국가직 7급 일반행정 제2차 공식 사업명과 과목명을 그대로 사용합니다.");
check("manager.exam-track-isolation", managerJs.includes("documentTrack(item)===track") && edge.includes("examTrackFromTitle(item.title) !== examTrack") && edge.includes("examTrackFromTitle(item.title)!==\"national\""), "국가직 위촉에는 국가직 원고만 선택·저장·시작할 수 있습니다.");
check("manager.official-assignment-title", managerJs.includes("syncOfficialAssignmentTitle") && edge.includes('`${subject.name} 핵심요약노트·모의고사 검수`') && edge.includes("title: assignmentTitle"), "위촉 과제명을 공식 과목명으로 자동 생성하고 서버에서 다시 확정합니다.");
check("manager.assignment-idempotency", managerJs.includes("assignmentSaving") && edge.includes("assignment_duplicate_prevented") && edge.includes('createError?.code === "23505"'), "연속 클릭과 동시 요청에서도 동일 위촉은 한 건만 유지합니다.");
check("manager.revoked-default-hidden", managerJs.includes('status==="all"?row.status!=="revoked"'), "종료한 위촉은 감사기록으로 보존하되 기본 운영 목록에서는 숨깁니다.");
check("manager.assignment-onboarding", edge.includes("전문위원 검수 개시 안내") && edge.includes("담당 검수 자료") && edge.includes("워크룸 이용 절차"), "계약 완료 후 품위 있는 안내장에 담당 자료와 전체 검수 절차를 자동 안내합니다.");
check("manager.communication-audit", managerHtml.includes('id="communication-audit"') && managerHtml.includes('id="communication-preview-frame"') && managerJs.includes("managerGetCommunicationAudit") && edge.includes('action === "managerGetCommunicationAudit"') && edge.includes("ensureManager(admin, userId)"), "대표가 수신자·제목·접수시각·메일 양식을 관리자 전용 읽기 화면에서 확인합니다.");
check("manager.communication-preview-repeat", managerJs.includes("function replaceCommunicationPreview") && managerJs.includes('previous.replaceWith(frame)') && managerJs.indexOf('showModal();renderCommunicationTab("start")') > -1, "발송 안내를 반복해서 열어도 미리보기 프레임을 새로 생성하여 회색 빈 화면을 방지합니다.");
check("manager.auto-refresh", managerJs.includes("AUTO_REFRESH_MS=30000") && managerJs.includes("scheduleAutoRefresh") && managerJs.includes("visibilitychange") && managerJs.includes('document.querySelector("dialog[open]")') && managerHtml.includes('class="sync-status"'), "관제 현황은 30초마다 자동 갱신하고 대화상자 작업 중에는 안전하게 보류하며 실제 확인 시각을 표시합니다.");
check("manager.complete-block-counts", edge.includes('review_block_counts') && edge.includes('fetchAllPages') && edge.includes('검수 문단이 준비되지 않은 원고'), "관리자 분모·검수완전성·보고서가 1,000행 제한 없이 전체 문단을 집계하고 문단 없는 원고는 시작을 차단합니다.");
check("manager.supplemental-guide", managerHtml.includes("개별 보충 안내") && managerJs.includes("renderCommunicationTab") && edge.includes("buildSupplementalGuideEmail") && edge.includes("buildSupplementalGuideText") && !managerJs.includes('api("managerSendSupplement'), "개별 보충 안내는 품위 있는 양식으로 미리보기·복사하되 자동 재발송하지 않습니다.");
check("database.notification-archive", notificationArchiveSql.includes("review_notification_archive") && notificationArchiveSql.includes("enable row level security") && notificationArchiveSql.includes("revoke all") && edge.includes('admin.from("review_notification_archive")'), "향후 발송 메일 원문은 일반 대시보드 활동기록과 분리된 대표 전용 보관함에 저장합니다.");
check("manager.prepared-gate", edge.includes('status: "prepared"') && edge.includes("held_until_batch_start") && edge.includes("계약과 최신 원고의 최종 확인이 진행 중입니다"), "계약·원고 최종 확인 전에는 전문위원 접근이 열리지 않습니다.");
check("manager.batch-start", managerHtml.includes("batch-start-dialog") && managerJs.includes("managerBatchStart") && edge.includes('action === "managerBatchStart"'), "대표님의 확인 후 국가직 과제를 한꺼번에 시작합니다.");
check("manager.single-start", managerHtml.includes('id="start-assignment"') && managerJs.includes("startSingleAssignment") && managerJs.includes("assignmentIds:[assignmentId]"), "계약 완료 시 전문위원별로 검수를 개별 시작하고 안내장을 발송합니다.");
check("manager.start-tracking", managerJs.includes("개시 승인") && managerJs.includes("인증번호 요청") && managerJs.includes("로그인 성공") && managerJs.includes("워크룸 접속") && managerJs.includes("첫 원고 열람") && managerJs.includes("발송 서비스 접수 완료") && edge.includes("workroomEnteredAt") && edge.includes("firstDocumentOpenedAt") && edge.includes("firstReviewRecordedAt") && edge.includes('event.reviewer_user_id === assignment.reviewer_user_id'), "관리자 시작 이벤트와 인증·실제 접속·원고 열람·검수 기록을 분리하여 표시합니다.");
check("manager.email-event-fallback", edge.includes('startNotificationStatus === "sent" ? startEvent?.occurred_at') && edge.includes('notificationRecordStatus:startEventError?"assignment_record_only"') && edge.includes("notificationSentAt,notificationId:notification.id"), "메일 접수 시각을 과제와 감사 이벤트에 이중 기록하고 기존 발송 성공 이벤트도 소급 인정합니다.");
check("manager.start-email-before-access", edge.includes('update({started_at:reservationAt})') && edge.includes('eq("status","prepared").is("started_at",null)') && edge.indexOf("notification=await sendOperationalEmail") < edge.indexOf('update({status:"assigned",notification_sent_at:notificationSentAt})'), "준비 상태의 원자적 예약으로 중복 발송을 막고 이메일 서비스 접수 후에만 과제 접근을 엽니다.");
check("manager.start-failure-retry", edge.includes('event_type:"assignment_start_failed"') && edge.includes('notificationRecordStatus:"email_failed"') && edge.includes('started:false'), "발송 실패 시 과제를 준비 상태로 유지하고 실패 기록과 재시도 가능 상태를 반환합니다.");
check("manager.start-confirmation-dialog", managerHtml.includes('id="start-result-dialog"') && managerJs.includes("showStartResult") && managerJs.includes("서버에서 다시 확인했습니다") && managerJs.includes("발송 서비스 접수 완료"), "짧은 토스트 대신 서버 재조회 결과를 닫기 전까지 유지되는 완료창으로 표시합니다.");
check("manager.launch-readiness", edge.includes("launchReadiness") && managerJs.includes("state.launchReadiness?.enabled") && managerJs.includes("메일 발송 서비스 연결 필요"), "시작·접근·메일 설정이 모두 준비됐을 때만 개별 시작 버튼을 활성화하고 부족한 설정을 정확히 표시합니다.");
check("manager.runtime-controls", managerHtml.includes('id="runtime-controls"') && managerHtml.includes('id="runtime-controls-dialog"') && managerJs.includes("managerSetRuntimeControls") && edge.includes('action === "managerSetRuntimeControls"') && edge.includes("runtime_controls_unlocked") && runtimeControlSql.includes("review_runtime_controls") && runtimeControlSql.includes("revoke all"), "관리자 화면에서 검수 개시 준비 잠금을 안전하게 해제·재잠금하고 변경 이력을 남깁니다.");
check("manager.runtime-start-separation", managerHtml.includes("잠금 해제만으로는 이메일 발송이나 원고 공개가 시작되지 않습니다") && managerJs.includes("아직 이메일과 원고는 전달되지 않았습니다") && edge.includes('action === "managerBatchStart"'), "운영 잠금 해제와 실제 전문위원 일괄 시작을 별도 확인 단계로 유지합니다.");
check("manager.batch-scale", edge.includes("assignmentIds.length > 50") && edge.includes("1~50건"), "초·중등 전문위원 22명을 포함해 최대 50개 과제를 한 번에 선택하고 서버에서 순차 시작할 수 있습니다.");
check("manager.email-lock", edge.includes("전문위원 안내 발송 기능이 현재 잠겨 있습니다") && edge.includes("!controls.launchEnabled || !controls.accessEnabled || !REVIEW_EMAIL_ENABLED || !REVIEW_EMAIL_PROVIDER"), "발송·접근·시작 설정 중 하나라도 잠기면 과제 시작과 이메일 발송이 함께 차단됩니다.");
check("manager.start-idempotency", edge.includes("existingStartArchive") && edge.includes("repaired_from_archive") && edge.includes("start_in_progress") && edge.includes('.is("started_at",null)') && edge.includes('"Idempotency-Key": idempotencyKey'), "동시 클릭·일시 장애에도 공급자 중복방지 키와 시작 기록 복구로 안내 메일 중복 발송을 막습니다.");
check("api.access-lock", edge.includes("전문위원 검수 접근은 대표님의 최종 시작 승인 전까지 안전하게 잠겨 있습니다") && edge.includes("if (!controls.accessEnabled)"), "대표님의 최종 승인 전에는 전문위원 로그인 후에도 검수 자료가 열리지 않습니다.");
check("manager.interim-report", html.includes("interim-submit") && managerHtml.includes("download-interim-report") && edge.includes('action === "submitInterimReport"') && edge.includes('action === "managerGetInterimReport"'), "전문위원의 중간보고 제출과 관리자 수신·다운로드가 연결됩니다.");
check("manager.launch-schedule", managerJs.includes('startsAt: "2026-08-13"') && managerJs.includes('interimDueAt: "2026-08-19"') && managerJs.includes('endsAt: "2026-08-22"'), "국가직 위촉·중간보고·최종완료 일정이 확정일로 고정됩니다.");
check("database.interim-report", batchSql.includes("review_interim_reports") && batchSql.includes("interim_due_at") && batchSql.includes("revoke all on table public.review_interim_reports"), "중간보고와 제출기한을 보호 테이블에 기록합니다.");
check("content.version-integrity", edge.includes("source_sha256") && edge.includes("최신 활성 원고와 원본 무결성값") && managerJs.includes("sourceSha256"), "활성 원고의 버전·무결성값을 서버와 운영 화면에서 확인합니다.");
check("manager.audit-preservation", edge.includes("이미 검수 기록이 시작된 과제의 자료 구성은 변경할 수 없습니다") && edge.includes("기존 기록을 보존하고 새 과제로 등록"), "진행·전달된 검수 기록을 관리자가 덮어쓰지 못합니다.");
check("manager.notifications", edge.includes("https://api.brevo.com/v3/smtp/email") && edge.includes("BREVO_API_KEY") && edge.includes("https://api.resend.com/emails") && edge.includes("notification_sent_at"), "Brevo를 우선 사용하고 Resend를 예비 수단으로 유지하며 위촉·재검토 안내 이메일을 기록합니다.");
check("security.watermark", js.includes("updateWatermark") && html.includes("watermark-layer") && css.includes("opacity: .055"), "식별 가능한 범위에서 원고 가독성을 해치지 않도록 완화한 개인 워터마크가 작동합니다.");
check("security.copy-print", js.includes("copy_blocked") && css.includes("@media print"), "복사와 인쇄를 제한합니다.");
check("security.frame-block", js.includes("window.top !== window.self") && js.includes("Embedded review access blocked"), "외부 사이트의 화면 삽입을 차단합니다.");
check("security.headers", headers.includes("Cache-Control: no-store") && headers.includes("Content-Security-Policy"), "보호 열람 응답 헤더가 정의되어 있습니다.");
check("production.paid-project-guard", productionInfrastructureVerifier.includes('ref: "lpxbfggwptsmxdxvnwhy"') && productionInfrastructureVerifier.includes('organizationName: "imyong-service"') && productionInfrastructureVerifier.includes('plan: "Pro"') && productionInfrastructureVerifier.includes('minimumCompute: "Micro"'), "운영 검수 시스템이 유료 Pro 조직·Micro 이상 프로젝트만 허용합니다.");
check("database.migration-parity", ["20260813000000_review_change_history.sql","20260813010000_fix_national_subject_names.sql","20260813011000_review_assignment_idempotency.sql","20260813020000_restore_unstarted_assignments.sql","20260813024000_owner_reset_review_launch.sql","20260814000000_review_runtime_controls.sql","20260814010000_review_report_workflow.sql","20260814020000_review_integrity_tracking.sql","20260814040000_review_notification_archive.sql","20260814050000_review_block_count_integrity.sql"].every((file) => migrationFiles.includes(file)) && !migrationFiles.includes("20260813003000_review_assignment_idempotency.sql"), "운영 적용 마이그레이션과 정식 소스 이력을 일치시킵니다.");
check("database.official-subjects", migrations.includes("when 'constitution' then '헌법'") && migrations.includes("when 'economics' then '경제학'") && migrations.includes("when 'administrative-law' then '행정법'") && migrations.includes("when 'public-administration' then '행정학'"), "국가직 7급 공식 과목명 헌법·경제학·행정법·행정학을 고정합니다.");
check("database.rls", sql.includes("enable row level security") && sql.includes("revoke all on table"), "검수 테이블 직접 접근을 차단합니다.");
check("database.private-source", sql.includes("review-masters") && sql.includes("public, file_size_limit") && sql.includes("false,"), "원본 저장소가 비공개로 정의됩니다.");
check("database.report-queue", sql.includes("create table if not exists public.review_exports") && sql.includes("delivery_status"), "최종 보고서가 교재 생성 시스템 인계 대기열에 보관됩니다.");
check("database.change-history", historySql.includes("review_change_history") && edge.includes("annotation_deleted") && edge.includes("progress_saved") && edge.includes("report_submitted"), "의견 수정·삭제·메모·보고서 제출의 변경 이력을 별도 보존합니다.");
check("api.auth", edge.includes("auth.getUser") && edge.includes("reviewer_user_id"), "보호 API가 로그인 사용자와 과제 배정을 함께 확인합니다.");
check("api.annotation-ownership", edge.includes("existingAnnotation.reviewer_user_id !== userId"), "다른 검수위원의 의견 ID를 덮어쓸 수 없습니다.");
check("api.server-completion", edge.includes("new Set<string>(progress.checkedBlocks") && edge.includes("checkedBlocks.length === validIds.size") && edge.includes("existingProgress?.completed_at || savedAt") && !edge.includes("progress.completedAt ||"), "중복 문단 ID와 클라이언트 시각으로 검수 완료를 위조할 수 없습니다.");
check("api.integrity-valid-ids", edge.includes("mergedCheckedBlockIds(progressMap.get(documentId), documentCheckRows, validBlockIds)") && edge.includes("if (!integrity.totalBlockCount)"), "과거·변조 ID를 집계에서 제외하고 빈 원고 제출을 차단합니다.");
check("api.check-record-retry", js.includes("blockCheckJobs") && js.includes("flushBlockChecks") && js.includes("연결이 회복되는 대로 자동으로 다시 저장"), "문단 열람·확인 시각 기록도 연결 장애 뒤 자동 복구합니다.");
check("api.event-record-retry", js.includes("EVENT_QUEUE_STORAGE_KEY") && js.includes("flushEventQueue") && js.includes("clientEventId") && edge.includes('contains("payload", { clientEventId })'), "접속·원고 열람 이벤트를 기기별 대기열에 보존하고 중복 없이 자동 재전송합니다.");
check("api.confirmation-recovery", edge.includes("mergedCheckedBlockIds") && edge.includes("first_checked_at") && edge.includes("checkedBlockIds"), "자동저장과 확인시각 중 한 경로가 중단되어도 실제 확인 문단을 복원하여 보고서·관제에 반영합니다.");
check("api.no-store", edge.includes('"Cache-Control": "no-store'), "API 응답을 브라우저 캐시에 남기지 않습니다.");
check("api.workflow", ["getDocument", "saveAnnotation", "saveProgress", "submitAssignment", "logEvent"].every((value) => edge.includes(`action === "${value}"`)), "열람·검수·제출·감사 흐름이 연결됩니다.");
check("api.report-export", edge.includes('action === "exportReport"') && edge.includes("createReviewReport") && edge.includes('crypto.subtle.digest("SHA-256"'), "서버가 보고서 원본과 무결성 해시를 생성합니다.");
check("api.report-identity", ["mobile", "organization", "department", "position_title"].every((value) => edge.includes(value)), "보고서에 검수위원 인적사항이 자동 결합됩니다.");

const failed = checks.filter((item) => !item.condition);
for (const item of checks) console.log(`${item.condition ? "PASS" : "FAIL"} ${item.name} - ${item.detail}`);
if (failed.length) {
  console.error(`\n${failed.length} review workroom checks failed.`);
  process.exit(1);
}
console.log(`\n${checks.length} review workroom checks passed.`);
