insert into public.review_subjects (program_id, code, name, sort_order) values
  ('civil', 'constitution', '헌법', 10),
  ('civil', 'economics', '경제학', 20),
  ('civil', 'administrative-law', '행정법', 30),
  ('civil', 'public-administration', '행정학', 40),
  ('elementary', 'integrated-curriculum', '초등 교육과정 통합', 10),
  ('elementary', 'teacher-essay', '교직논술', 20),
  ('elementary', 'kindergarten', '유치원', 30),
  ('elementary', 'elementary-special', '초등특수', 40),
  ('secondary', 'korean', '국어', 10),
  ('secondary', 'english', '영어', 20),
  ('secondary', 'mathematics', '수학', 30),
  ('secondary', 'history', '역사', 40),
  ('secondary', 'general-social-studies', '일반사회', 50),
  ('secondary', 'ethics', '도덕·윤리', 60),
  ('secondary', 'physical-education', '체육', 70),
  ('secondary', 'mechanical-engineering', '기계', 80),
  ('secondary', 'plant-resources-landscape', '식물자원·조경', 90),
  ('secondary', 'commerce', '상업', 100),
  ('secondary', 'life-science', '생명과학', 110),
  ('secondary', 'information-computer', '정보·컴퓨터', 120),
  ('secondary', 'chinese', '중국어', 130),
  ('secondary', 'education-essay', '교육학논술', 140),
  ('secondary', 'music', '음악', 150),
  ('secondary', 'health', '보건', 160),
  ('secondary', 'art', '미술', 170),
  ('secondary', 'nutrition', '영양', 180),
  ('secondary', 'professional-counseling', '전문상담', 190)
on conflict (program_id, code) do update set name = excluded.name, sort_order = excluded.sort_order;
